/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.56
 * Generated at: 2020-08-05 07:24:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.review;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kh.banzi.review.model.vo.Attachment;
import java.util.ArrayList;
import com.kh.banzi.review.model.vo.PageInfo;
import com.kh.banzi.review.model.vo.Review;
import java.util.List;
import com.kh.banzi.user.model.vo.User;

public final class userReview_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/review/../common/header.jsp", Long.valueOf(1596610595358L));
    _jspx_dependants.put("/WEB-INF/views/review/../common/footer.jsp", Long.valueOf(1595989111466L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.kh.banzi.review.model.vo.Attachment");
    _jspx_imports_classes.add("com.kh.banzi.review.model.vo.PageInfo");
    _jspx_imports_classes.add("com.kh.banzi.user.model.vo.User");
    _jspx_imports_classes.add("com.kh.banzi.review.model.vo.Review");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 
 	PageInfo pInfo = (PageInfo)request.getAttribute("pInfo");
 	List<Review> rList = (List<Review>)request.getAttribute("rList");
 	ArrayList<Attachment> fList = (ArrayList<Attachment>)request.getAttribute("fList");
	String type = request.getParameter("type");

	int currentPage = pInfo.getCurrentPage();
	int listCount = pInfo.getListCount();
	int maxPage = pInfo.getMaxPage();
	int startPage = pInfo.getStartPage();
	int endPage = pInfo.getEndPage();
	int boardType = pInfo.getBoardType();
	
	int prev = (currentPage-1)/10*10; // < 버튼
	int next = (currentPage+9)/10*10+1; // > 버튼

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>  \r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("     <script src=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/js/all.min.js\"></script>\r\n");
      out.write("     <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("<title>사용후기</title>\r\n");
      out.write("<style>\r\n");
      out.write("        @font-face {\r\n");
      out.write("            font-family: 'KyoboHand';\r\n");
      out.write("            src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_20-04@1.0/KyoboHand.woff') format('woff');\r\n");
      out.write("            font-weight: normal;\r\n");
      out.write("            font-style: normal;\r\n");
      out.write("        }\r\n");
      out.write("        @font-face { \r\n");
      out.write("            font-family: 'IBMPlexSansKR-Light';\r\n");
      out.write("            src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_20-07@1.0/IBMPlexSansKR-Light.woff') format('woff');\r\n");
      out.write("            font-weight: normal; \r\n");
      out.write("            font-style: normal; \r\n");
      out.write("        }\r\n");
      out.write("        @font-face { \r\n");
      out.write("            font-family: 'GmarketSansMedium'; \r\n");
      out.write("            src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2001@1.1/GmarketSansMedium.woff') format('woff');\r\n");
      out.write("            font-weight: normal; \r\n");
      out.write("            font-style: normal; \r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body { margin: 0; padding: 0;}\r\n");
      out.write("        .empty { width: 100%; height: 200px;}\r\n");
      out.write("\r\n");
      out.write("        /* title */\r\n");
      out.write("        .review-1 {\r\n");
      out.write("            font-size: 30px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin: 10px;\r\n");
      out.write("            font-weight: bolder;\r\n");
      out.write("            font-family: \"yg-jalnan\";\r\n");
      out.write("            color: rgb(87, 87, 87);\r\n");
      out.write("            margin-bottom: 0px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .line-height {\r\n");
      out.write("            margin: auto;\r\n");
      out.write("            width: 130px;\r\n");
      out.write("            border: 1px solid grey;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* button */\r\n");
      out.write("        .review-button-area {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 80px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .review-button {\r\n");
      out.write("            width: 70px;\r\n");
      out.write("            height: 26px;\r\n");
      out.write("            border-radius: 13px;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            background-color: #ffce54;\r\n");
      out.write("            color: white;\r\n");
      out.write("            margin: 20px 16px 20px 16px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .review-button:hover {\r\n");
      out.write("            background-color: rgb(250, 156, 88);\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .review-button:hover>a {\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            text-decoration:none;\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .review-button>a {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            color: white;\r\n");
      out.write("            font-family: 'KyoboHand';\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("            line-height: 26px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin: auto;\r\n");
      out.write("            top: 0; bottom: 0; left: 0; right: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* review-box */\r\n");
      out.write("        .container {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 400px;\r\n");
      out.write("            margin-bottom: 0px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .review-box {\r\n");
      out.write("            width: 260px;\r\n");
      out.write("            height: 350px;\r\n");
      out.write("            border-radius: 14px;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            background-color: rgba(238, 238, 238, 0.2);\r\n");
      out.write("            border: 4px solid rgba(250, 156, 88, 0.3);\r\n");
      out.write("            margin: 25px;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .review-box:hover {\r\n");
      out.write("            background-color: rgba(149, 149, 149, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .review-box-top {\r\n");
      out.write("            height: 22%;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            border-bottom: 3px solid rgba(250, 156, 88, 0.3);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .circle-img {\r\n");
      out.write("            border: 1px solid black;\r\n");
      out.write("            width: 60px;\r\n");
      out.write("            height: 60px;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            float: left;\r\n");
      out.write("            border-radius: 100%;\r\n");
      out.write("            margin-top: 6px;\r\n");
      out.write("            margin-left: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .circle-img>img {\r\n");
      out.write("            margin: 4px 0px 0px 7px;\r\n");
      out.write("            width: 75%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .review-title {\r\n");
      out.write("            text-align: left;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            width: 60%;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            float: left;\r\n");
      out.write("            margin-left: 18px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .review-title-name {\r\n");
      out.write("            height: 60%;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            line-height: 48px;\r\n");
      out.write("            font-family: 'GmarketSansMedium';\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .review-title-heart {\r\n");
      out.write("            height: 40%;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            line-height: 15px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            font-family: 'GmarketSansMedium';\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .review-box-center {\r\n");
      out.write("            height: 26%;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            padding-top: 5px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .review-box-inside {\r\n");
      out.write("            width: 64px;\r\n");
      out.write("            height: 64px;\r\n");
      out.write("            margin: 7px 4px 3px 4px;\r\n");
      out.write("            \r\n");
      out.write("            border-radius: 2px;\r\n");
      out.write("            display: inline-flex;\r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .review-box-inside  img{\r\n");
      out.write("        \twidth: 100%;\r\n");
      out.write("        \theight: 100%;\r\n");
      out.write("        \t display: inline-flex;\r\n");
      out.write("        } \r\n");
      out.write("\r\n");
      out.write("        .review-box-bottom {\r\n");
      out.write("            height: 50%;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            text-align: left;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .review-box-bottom>p {\r\n");
      out.write("            font-family: \"IBMPlexSansKR-Light\";\r\n");
      out.write("            margin: 0px 14px 14px 14px;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 카테고리 button */\r\n");
      out.write("        #btn {\r\n");
      out.write("            background-color: #ffce54;\r\n");
      out.write("            border: none;\r\n");
      out.write("            float: right;\r\n");
      out.write("            margin-right: 240px;\r\n");
      out.write("        }\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* 페이징바 */\r\n");
      out.write("    \t.pagination {\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("        }\r\n");
      out.write("        #searchForm{\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #searchForm>*{\r\n");
      out.write("            top : 0;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .boardTitle > img{\r\n");
      out.write("        \twidth: 50px;\r\n");
      out.write("        \theight: 50px;\r\n");
      out.write("        }\r\n");
      out.write("      \t\r\n");
      out.write("      \t/* 평가 별*/\r\n");
      out.write("      \t.reviewStar .rating {\r\n");
      out.write("      \t\tcolor: #bababa;\r\n");
      out.write("      \t}\r\n");
      out.write("      \t\r\n");
      out.write("        .button-area {\r\n");
      out.write("            height: 0px;\r\n");
      out.write("            width: 65%;\r\n");
      out.write("            margin: auto;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .button-area .btn{\r\n");
      out.write("        \twidth: 80px;\r\n");
      out.write("\t\t    height: 38px;\r\n");
      out.write("\t\t    padding: 0px;\r\n");
      out.write("\t\t    border-radius: 10px;\r\n");
      out.write("\t\t    font-size: 18px;\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t    font-family: 'GmarketSansMedium'; \r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .for-hidden{\r\n");
      out.write("       \t margin:0px;\r\n");
      out.write("        }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write('\n');
      out.write('\n');
	
	User loginUser = (User)session.getAttribute("loginUser");

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("  <meta charset=\"UTF-8\" />\n");
      out.write("\n");
      out.write("  <!-- Required meta tags -->\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\n");
      out.write("  <!-- Bootstrap CSS -->\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css\"\n");
      out.write("    integrity=\"sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk\" crossorigin=\"anonymous\" />\n");
      out.write("  <!-- jQuery -->\n");
      out.write("  <script src=\"https://code.jquery.com/jquery-3.5.1.min.js\"></script>\n");
      out.write("\n");
      out.write("    <!-- CSS -->\n");
      out.write("   <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/style.css\">\n");
      out.write("\n");
      out.write("  <title>BAN JI</title>\n");
      out.write("  <style>\n");
      out.write("  \n");
      out.write("/* -------------- body -------------- */\n");
      out.write("\n");
      out.write("* {\n");
      out.write("/* border: 1px solid black; */\n");
      out.write("margin: 0;\n");
      out.write("padding: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".row>div {\n");
      out.write("width: 100%;\n");
      out.write("height: 100%;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* -------------- header -------------- */\n");
      out.write("header{\n");
      out.write("position: fixed;\n");
      out.write("height : 157px;\n");
      out.write("width: 100%;\n");
      out.write("z-index : 100;\n");
      out.write("background-color : white;\n");
      out.write("top : 0px;\n");
      out.write("}\n");
      out.write("#main-logo{\n");
      out.write("padding: 11px;\n");
      out.write("}\n");
      out.write("#header button {\n");
      out.write("float: right;\n");
      out.write("margin: 1em;\n");
      out.write("width: 6em;\n");
      out.write("height: 2em;\n");
      out.write("border: 1px solid lightgray;\n");
      out.write("font-family: \"InfinitySans-RegularA1\";\n");
      out.write("font-size: 0.7em;\n");
      out.write("color: lightgray;\n");
      out.write("background-color: transparent;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("/* -------------- nav -------------- */\n");
      out.write(".dropdown:hover .dropdown-menu { \n");
      out.write("display: block;\n");
      out.write("margin-top: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#nav{\n");
      out.write("border-top: 1px solid lightgray;\n");
      out.write("border-bottom: 1px solid lightgray;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#nav * {\n");
      out.write("font-family: \"InfinitySans-RegularA1\";\n");
      out.write("text-align: center;\n");
      out.write("vertical-align: middle;\n");
      out.write("border: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#nav a {\n");
      out.write("width: 10rem;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#nav li {\n");
      out.write("width: 10%;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".nav-link {\n");
      out.write("color: #3a3847;\n");
      out.write("width: 100%;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".nav-link:hover {\n");
      out.write("color: #ffce54;\n");
      out.write("border: none;\n");
      out.write("border-bottom: 3px solid !important;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dropdown-menu {\n");
      out.write("border-top: 5px solid transparent !important;\n");
      out.write("width: 10rem;\n");
      out.write("background-color: rgb(250, 250, 250);\n");
      out.write("box-shadow: 0 10px 10px lightgrey;\n");
      out.write("padding-bottom: 20px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dropdown-item {\n");
      out.write("font-size: small;\n");
      out.write("margin-top: 10px;\n");
      out.write("background-color: transparent;\n");
      out.write("opacity: 0.7;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dropdown-item:hover {\n");
      out.write("background-color: #ffce54;\n");
      out.write("color: white;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#userNameArea{\n");
      out.write("\tborder: none !important;\n");
      out.write("\tcolor: #3a3847 !important;\n");
      out.write("}\n");
      out.write("  </style>\n");
      out.write("  \n");
      out.write("  <!--------------------------------- sweet alert ---------------------------------------- -->\n");
      out.write("  <script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\n");
      out.write("  \n");
      out.write("  <script>\n");
      out.write("  ");

 	 String status = (String)(request.getSession().getAttribute("status"));
 	 String msg = (String)(request.getSession().getAttribute("msg"));
 	 String text = (String)(request.getSession().getAttribute("text"));
  
      out.write("\n");
      out.write("  \n");
      out.write("  ");
 if(msg != null){
      out.write("\n");
      out.write("\t\t \t swal({\n");
      out.write("\t\t \t\t icon : \"");
      out.print(status);
      out.write("\", \n");
      out.write("\t\t \t\t title : \"");
      out.print(msg);
      out.write("\",\n");
      out.write("\t\t \t\t text : \"");
      out.print(text != null ? text : "" );
      out.write("\" \n");
      out.write("\t\t \t });\n");
      out.write(" \t ");

 	 		session.removeAttribute("msg");
 	 		session.removeAttribute("status");
 	 		session.removeAttribute("text");
  	}
 	 
      out.write("\n");
      out.write("  \n");
      out.write("  </script>\n");
      out.write("  \n");
      out.write("<body>\n");
      out.write("  <header>\n");
      out.write("    <div class=\"container-fluid\">\n");
      out.write("      <!--  ------------ header ------------ -->\n");
      out.write("      <div class=\"row\" id=\"header\">\n");
      out.write("        <div class=\"col-md-4\">\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-md-4\">\n");
      out.write("          <a href=\"");
      out.print(request.getContextPath());
      out.write("\">\n");
      out.write("            <img src=\"");
      out.print(request.getContextPath());
      out.write("/resources/img/logo_main.png\" width=\"200px\" class=\"mx-auto d-block\" id=\"main-logo\">\n");
      out.write("          </a>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-md-4\">\n");
      out.write("          <button type=\"button\" onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/user/signUpAssign1.do'\">회원가입</button>\n");
      out.write("          \n");
      out.write("          ");
 if(loginUser == null) {
      out.write("\n");
      out.write("          \t <button type=\"button\" onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/userLogin/loginForm.do'\">로그인</button>\n");
      out.write("          ");
 } else{ 
      out.write("\n");
      out.write("          \t <button type=\"button\" onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/userLogin/logout.do'\">로그아웃</button>\n");
      out.write("          \t <button type=\"button\" id=\"userNameArea\" onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/myPage/changeUserForm.do'\">");
      out.print(loginUser.getUserName() );
      out.write(" 님</button>\n");
      out.write("          \t \n");
      out.write("          ");
 } 
      out.write("\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!--  ------------ nav ------------ -->\n");
      out.write("    <div class=\"row\" id=\"nav\">\n");
      out.write("      <div class=\"col-md-12\">\n");
      out.write("        <ul class=\"nav nav-tabs justify-content-center\" id=\"nav-wrapper\">\n");
      out.write("          <li class=\"nav-item dropdown\">\n");
      out.write("            <a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/user/introduce.do\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">구성원 소개</a>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"nav-item dropdown\">\n");
      out.write("            <a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/information/list.do?type=2&category=1\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">정보</a>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"nav-item dropdown\">\n");
      out.write("            <a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/qna/list.do\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">커뮤니티</a>\n");
      out.write("            <div class=\"dropdown-menu\">\n");
      out.write("              <a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath() );
      out.write("/notice/list.do\">공지사항</a>\n");
      out.write("              <a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/qna/list.do\">Q&A</a>\n");
      out.write("              <a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/community/list.do\">자유 게시판</a>\n");
      out.write("              <a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/review/review.do?type=6\">사용 후기</a>\n");
      out.write("            </div>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"nav-item dropdown\">\n");
      out.write("            <a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/event/eventList.do?type=1\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">이벤트</a>\n");
      out.write("            <div class=\"dropdown-menu\">\n");
      out.write("              <a class=\"dropdown-item\"  href=\"");
      out.print(request.getContextPath());
      out.write("/event/eventList.do?type=1\">진행중인 이벤트</a>\n");
      out.write("              <a class=\"dropdown-item\"  href=\"");
      out.print(request.getContextPath());
      out.write("/event/pastList.do?type=2\">종료된 이벤트</a>\n");
      out.write("              <a class=\"dropdown-item\"  href=\"");
      out.print(request.getContextPath());
      out.write("/event/winnerList.do?type=2\">이벤트 당첨자</a>\n");
      out.write("            </div>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"nav-item dropdown\">\n");
      out.write("          \t ");
 if(loginUser != null && loginUser.getUserId().equals("master")){ 
      out.write("\n");
      out.write("          \t \n");
      out.write("          \t\t<a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/masterPage/userAuthList.do\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">관리자 페이지</a>\n");
      out.write("            \n");
      out.write("\t\t\t\t\t\t");
 }else { 
      out.write("\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("            <a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/myPage/changeUserForm.do\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">마이페이지</a>\n");
      out.write("            <div class=\"dropdown-menu\">\n");
      out.write("              <a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/myPage/changeUserForm.do\">회원정보 수정</a>\n");
      out.write("              <a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/myPage/changePwdForm.do\">비밀번호 수정</a>\n");
      out.write("              <a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/myPage/secessionForm.do\">회원 탈퇴</a>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("          </li>\n");
      out.write("        </ul>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </header>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("  <script>\n");
      out.write("    $(function () {\n");
      out.write("      $(\".nav-link\").on(\"mouseenter\", function () {\n");
      out.write("        var idx = $(this).index(\".nav-link\");\n");
      out.write("\n");
      out.write("        $(\".nav-link\").each(function (index, item) {\n");
      out.write("          if (index == idx) {\n");
      out.write("            $(item)\n");
      out.write("              .css(\"color\", \"#ffce54\")\n");
      out.write("              .css(\"border-bottom\", \"3px solid #ffce54\");\n");
      out.write("          } else {\n");
      out.write("            $(item).css(\"color\", \"#3a3847\").css(\"border-bottom\", \"none\");\n");
      out.write("          }\n");
      out.write("        });\n");
      out.write("      });\n");
      out.write("\n");
      out.write("      $(\"#nav\").on(\"mouseleave\", function () {\n");
      out.write("        $(\".nav-link\")\n");
      out.write("          .css(\"color\", \"#3a3847\")\n");
      out.write("          .css(\"border-bottom\", \"3px solid transparent\");\n");
      out.write("      });\n");
      out.write("    });\n");
      out.write("  </script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js\"\n");
      out.write("    integrity=\"sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo\"\n");
      out.write("    crossorigin=\"anonymous\"></script>\n");
      out.write("  <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js\"\n");
      out.write("    integrity=\"sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI\"\n");
      out.write("    crossorigin=\"anonymous\"></script>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<p class=\"empty\"></p>\r\n");
      out.write("    <div class=\"review-1\">사용후기</div>\r\n");
      out.write("    <p class=\"line-height\"></p>\r\n");
      out.write("\r\n");
      out.write("    <!-- 버튼부분 -->\r\n");
      out.write("    <div class=\"review-button-area\">\r\n");
      out.write("        <div class=\"review-button\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/review/reviewCategory.do?type=");
      out.print(type);
      out.write("&category=1\">병 원</a></div>\r\n");
      out.write("        <div class=\"review-button\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/review/reviewCategory.do?type=");
      out.print(type);
      out.write("&category=2\">사 료</a></div>\r\n");
      out.write("        <div class=\"review-button\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/review/reviewCategory.do?type=");
      out.print(type);
      out.write("&category=3\">간 식</a></div>\r\n");
      out.write("        <div class=\"review-button\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/review/reviewCategory.do?type=");
      out.print(type);
      out.write("&category=4\">용 품</a></div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\t");
if(rList.isEmpty()){ 
      out.write("\r\n");
      out.write("    \t<table><tr><td colspan=\"6\" align=\"center\">존재하는 게시글이 없습니다.</td></tr></table>\r\n");
      out.write("  \t");
 }else{ 
      out.write("\r\n");
      out.write("   \t\r\n");
      out.write("    <!-- 1 -->\r\n");
      out.write("\t");
int num=0; 
      out.write("\r\n");
      out.write("\t   \t");
for(int i=0; i<3; i++){ 
      out.write("\r\n");
      out.write("\t    <div class=\"container\">\r\n");
      out.write("\t    \t");
for(int j=0; j<3; j++){ 
      out.write("\r\n");
      out.write("   \t\t\r\n");
      out.write("        <!--review box 1-1-->\r\n");
      out.write("        <div class=\"review-box\">\r\n");
      out.write("\t    <p class=\"for-hidden\" id=\"");
      out.print(rList.get(num).getReviewBoardNo() );
      out.write("\">\r\n");
      out.write("            <div class=\"review-box-top\">\r\n");
      out.write("            \t");
 if(rList.get(num).getReviewBoardNo() %2 == 0){ 
      out.write("\r\n");
      out.write("                <div class=\"circle-img\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/resources/img/개아이콘.png\"></div>\r\n");
      out.write("                ");
}else{ 
      out.write("\r\n");
      out.write("                <div class=\"circle-img\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/resources/img/개아이콘2.png\"></div>\r\n");
      out.write("                ");
} 
      out.write("\r\n");
      out.write("                <div class=\"review-title\">\r\n");
      out.write("                    <div class=\"review-title-name\">");
      out.print(rList.get(num).getUserName());
      out.write("님</div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"review-title-heart\">\r\n");
      out.write("                    <div class=\"reviewStar\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"rating\" data-rate=\"");
      out.print(rList.get(num).getReviewRating());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fas fa-star\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fas fa-star\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fas fa-star\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fas fa-star\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fas fa-star\"></i>\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div> <!-- review_top end -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("            <div class=\"review-box-center\">\r\n");
      out.write("            <!-- 이미지 미리보기 3개 -->\r\n");
      out.write("           \t\t");
 
           			String path = request.getContextPath() + "/resources/uploadImages/";
           			String[] img = new String[3];
           			for(Attachment at : fList ) {
           			if(at.getParentBoardNo() == rList.get(num).getReviewBoardNo()){
           				switch(at.getFileLevel()){
           				case 0 : img[0] = path + at.getFileChangeName(); break;
           				case 1 : img[1] = path + at.getFileChangeName(); break;
           				case 2 : img[2] = path + at.getFileChangeName(); break;
           				}
           			}
           			
           		}
      out.write("\r\n");
      out.write("                <div class=\"review-box-inside\">\r\n");
      out.write("                \t");
 if(img[0] != null) {
      out.write("\r\n");
      out.write("                \t\t<img src = \"");
      out.print(img[0] );
      out.write("\">\r\n");
      out.write("                \t");
 } 
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"review-box-inside\">\r\n");
      out.write("                \t");
 if(img[1] != null) {
      out.write("\r\n");
      out.write("                \t\t<img src = \"");
      out.print(img[1] );
      out.write("\">\r\n");
      out.write("                \t");
 } 
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"review-box-inside\">\r\n");
      out.write("                \t");
 if(img[2] != null) {
      out.write("\r\n");
      out.write("                \t\t<img src = \"");
      out.print(img[2] );
      out.write("\">\r\n");
      out.write("                \t");
 } 
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"review-box-bottom\">\r\n");
      out.write("                <p>");
      out.print(rList.get(num).getReviewContent() );
      out.write("</p>\r\n");
      out.write("            </div>\r\n");
      out.write("    \t</p> <!-- 연결위한 div end -->\r\n");
      out.write("        </div> <!-- review-box end -->\r\n");
      out.write("\t\t");
num++; } 
      out.write("\r\n");
      out.write("    \t</div> <!-- container end -->\r\n");
      out.write("       ");
} 
      out.write("\r\n");
      out.write("      ");
} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("\t\t");
 if(loginUser != null){ 
      out.write("\r\n");
      out.write("   \t\t\t <div class=\"button-area\">\r\n");
      out.write("\t\t        <button type=\"button\" class=\"btn btn-info btn-lg\" id=\"btn\" onclick=\"location.href='writeReviewForm.do?type=");
      out.print(type);
      out.write("';\">글쓰기</button>\r\n");
      out.write("            </div>\r\n");
      out.write("\t\t");
} 
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t<!-- 페이징바 -->\r\n");
      out.write("\t        <div style=\"clear:both\">\r\n");
      out.write("\t        \t<ul class=\"pagination\">\r\n");
      out.write("\t        \t\t");
if(currentPage>10){ 
      out.write("\r\n");
      out.write("\t        \t\t\t<li>\r\n");
      out.write("\t        \t\t\t\t<a class=\"page-link\"  href=\"");
      out.print(request.getContextPath());
      out.write("/review/review.do?type=");
      out.print(type);
      out.write("&cp=1\">&lt;&lt;</a>\r\n");
      out.write("\t        \t\t\t</li>\r\n");
      out.write("\t        \t\t\t<li>\r\n");
      out.write("\t        \t\t\t<a class=\"page-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/review/review.do?type=");
      out.print(type);
      out.write("&cp=");
      out.print(prev);
      out.write("\">&lt;</a>\r\n");
      out.write("\t        \t\t\t</li>\r\n");
      out.write("\t        \t\t\t");
} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t        \t\t\t");
for(int p=startPage; p<endPage; p++){ 
      out.write("\r\n");
      out.write("\t        \t\t\t\t");
if(p == currentPage){ 
      out.write("\r\n");
      out.write("\t        \t\t\t\t\t<li><a class=\"page-link\">");
      out.print(p);
      out.write("</a></li>\r\n");
      out.write("\t        \t\t\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t        \t\t\t\t\t<li>\r\n");
      out.write("\t        \t\t\t\t\t\t<a class=\"page-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/review/review.do?type=");
      out.print(type);
      out.write("&cp=");
      out.print(p);
      out.write('"');
      out.write('>');
      out.print(p );
      out.write("</a>\r\n");
      out.write("\t        \t\t\t\t\t</li>\r\n");
      out.write("\t        \t\t\t\t\t\r\n");
      out.write("\t        \t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t        \t\t\t");
} 
      out.write("\r\n");
      out.write("\t        \t\t\t\r\n");
      out.write("\t        \t\t\t");
if(next <maxPage){ 
      out.write("\r\n");
      out.write("\t        \t\t\t\t<li>\r\n");
      out.write("\t        \t\t\t\t\t<a class=\"page-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/review/review.do?type=");
      out.print(type);
      out.write("&cp=");
      out.print(next);
      out.write("\">&gt;</a>\r\n");
      out.write("\t        \t\t\t\t</li>\r\n");
      out.write("\t        \t\t\t\t<li>\r\n");
      out.write("\t        \t\t\t\t\t<a class=\"page-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/review/review.do?type=");
      out.print(type);
      out.write("&cp=");
      out.print(maxPage);
      out.write("\">&gt;&gt;</a>\r\n");
      out.write("\t        \t\t\t\t</li>\r\n");
      out.write("\t        \t\t\t");
} 
      out.write("\r\n");
      out.write("\t        \t</ul>\r\n");
      out.write("\t        </div> <!-- 페이징바 end -->\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>마이페이지</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("           .footer {\r\n");
      out.write("            background: #ffffff;\r\n");
      out.write("            font-family: \"yg-jalnan\";\r\n");
      out.write("            color: #3a3847;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .footer .col-xs-12{\r\n");
      out.write("            margin-top: 1em;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .footer .contact i {\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            font-family: \"InfinitySans-RegularA1\";\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .footer .copyright p {\r\n");
      out.write("            border-top: 1px solid lightgray;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        .footer img{\r\n");
      out.write("            width: 10em;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .footer p{\r\n");
      out.write("            font-family: \"InfinitySans-RegularA1\";\r\n");
      out.write("            color: #3a3847;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .footer h4{\r\n");
      out.write("            margin-bottom: 0.5em;\r\n");
      out.write("        }\r\n");
      out.write("       \r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <div class=\"footer\">\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("            <div class=\"row mt-5\">\r\n");
      out.write("                <div class=\"col copyright\">\r\n");
      out.write("                    <p></p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row mt-3\">\r\n");
      out.write("            \t<div class=\"col-md-2\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-3\">\r\n");
      out.write("                    <img src=\"");
      out.print(request.getContextPath());
      out.write("/resources/img/logo_footer.png\"\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-3\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-4 contact\">\r\n");
      out.write("                    <h4 class=\"mt-md-0 mt-sm-4\">contact us</h4>\r\n");
      out.write("                    <p>서울특별시 중구 남대문로 120 대일빌딩 2F</p>\r\n");
      out.write("                    <p>1544-9970</p>\r\n");
      out.write("                    <p>info@email.com</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row mt-3\">\r\n");
      out.write("                <div class=\"col copyright\">\r\n");
      out.write("                    <p class=\"\"><small>© 2020. All Rights Reserved.</small></p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js\"\r\n");
      out.write("        integrity=\"sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo\"\r\n");
      out.write("        crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js\"\r\n");
      out.write("        integrity=\"sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI\"\r\n");
      out.write("        crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t// 평가 등급 (+targetScore값이 변경값)\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t    var rating = $('.reviewStar .rating');\r\n");
      out.write("\t    rating.each(function(){\r\n");
      out.write("\t        var targetScore = $(this).attr('data-rate');\r\n");
      out.write("\t        console.log(targetScore);\r\n");
      out.write("\t        $(this).find('svg:nth-child(-n+' + targetScore +')').css({color:'#FFD600'})\r\n");
      out.write("\t    });\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t// 페이지 이전\r\n");
      out.write("\t$(\".review-box\").on(\"click\", function(){\r\n");
      out.write("\t    var boardNo = $(this).children().attr(\"id\");\r\n");
      out.write("        \r\n");
      out.write("        // boardType이 안보내지면 null뜸 why?\r\n");
      out.write("        location.href = \"");
      out.print(request.getContextPath());
      out.write("/review/detailReview.do?type=");
      out.print(boardType);
      out.write("&no=\" + boardNo;\r\n");
      out.write("     }).on(\"mouseenter\", function(){\r\n");
      out.write("   \t  $(this).parent().css(\"cursor\", \"pointer\");\r\n");
      out.write("     });\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
