/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.56
 * Generated at: 2020-08-05 07:24:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.review;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kh.banzi.review.model.vo.Attachment;
import java.util.ArrayList;
import com.kh.banzi.review.model.vo.Review;
import com.kh.banzi.user.model.vo.User;
import com.kh.banzi.review.model.vo.Review;
import com.kh.banzi.user.model.vo.User;

public final class userReviewDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/views/review/reviewRelpy.jsp", Long.valueOf(1596499515312L));
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1596610595358L));
    _jspx_dependants.put("/WEB-INF/views/review/../common/footer.jsp", Long.valueOf(1595989111466L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.kh.banzi.review.model.vo.Attachment");
    _jspx_imports_classes.add("com.kh.banzi.user.model.vo.User");
    _jspx_imports_classes.add("com.kh.banzi.review.model.vo.Review");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 
	Review review = (Review)request.getAttribute("review");
	ArrayList<Attachment> fList = (ArrayList<Attachment>)request.getAttribute("fList");
	String cp = request.getParameter("cp");
	String type = request.getParameter("type");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>사용 후기 게시글</title>\r\n");
      out.write("<style>\r\n");
      out.write("\t#board-area{ margin-bottom:100px;}\r\n");
      out.write("\t#board-content{ padding-bottom:150px;}\r\n");
      out.write("\t.boardImgArea{ height: 300px;}\r\n");
      out.write("\t*{ font-family: \"InfinitySans-RegularA1\"; }\r\n");
      out.write("\t\r\n");
      out.write("\t.boardImg{\r\n");
      out.write("\t\twidth : 100%;\r\n");
      out.write("\t\theight: 100%;\r\n");
      out.write("\t\tmax-width : 300px;\r\n");
      out.write("\t\tmax-height: 300px;\r\n");
      out.write("\t\tmargin : auto;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.carousel-control-prev-icon {\r\n");
      out.write(" \t\tbackground-image: url(\"data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' fill='%23000' viewBox='0 0 8 8'%3E%3Cpath d='M5.25 0l-4 4 4 4 1.5-1.5-2.5-2.5 2.5-2.5-1.5-1.5z'/%3E%3C/svg%3E\") !important;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.carousel-control-next-icon {\r\n");
      out.write("  \t\tbackground-image: url(\"data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' fill='%23000' viewBox='0 0 8 8'%3E%3Cpath d='M2.75 0l-1.5 1.5 2.5 2.5-2.5 2.5 1.5 1.5 4-4-4-4z'/%3E%3C/svg%3E\") !important;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.replyWrite > table{\r\n");
      out.write("\t\twidth: 90%;\r\n");
      out.write("\t\talign: center;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#replyContentArea{ width: 90%; }\r\n");
      out.write("\t\r\n");
      out.write("\t#replyContentArea > textarea{\r\n");
      out.write("\t    resize: none;\r\n");
      out.write("    \twidth: 100%;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#replyBtnArea{\r\n");
      out.write("\t    width: 100px;\r\n");
      out.write("\t    text-align: center;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.rWriter{ margin-right: 30px;}\r\n");
      out.write("\t.rDate{\r\n");
      out.write("\t\tfont-size: 0.7em;\r\n");
      out.write("\t\tcolor : gray;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#replyListArea{ list-style-type: none; }\r\n");
      out.write("\r\n");
      out.write("\t#listBtn, #deleteBtn,#updateBtn {\r\n");
      out.write("    background-color:#ffce54;\r\n");
      out.write("    border-color:white;\r\n");
      out.write("    }\r\n");
      out.write("    #imgArea{\r\n");
      out.write("    \twidth:700px;\r\n");
      out.write("    \theight:300px;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write('\n');
      out.write('\n');
	
	User loginUser = (User)session.getAttribute("loginUser");

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("  <meta charset=\"UTF-8\" />\n");
      out.write("\n");
      out.write("  <!-- Required meta tags -->\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\n");
      out.write("  <!-- Bootstrap CSS -->\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css\"\n");
      out.write("    integrity=\"sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk\" crossorigin=\"anonymous\" />\n");
      out.write("  <!-- jQuery -->\n");
      out.write("  <script src=\"https://code.jquery.com/jquery-3.5.1.min.js\"></script>\n");
      out.write("\n");
      out.write("    <!-- CSS -->\n");
      out.write("   <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/style.css\">\n");
      out.write("\n");
      out.write("  <title>BAN JI</title>\n");
      out.write("  <style>\n");
      out.write("  \n");
      out.write("/* -------------- body -------------- */\n");
      out.write("\n");
      out.write("* {\n");
      out.write("/* border: 1px solid black; */\n");
      out.write("margin: 0;\n");
      out.write("padding: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".row>div {\n");
      out.write("width: 100%;\n");
      out.write("height: 100%;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* -------------- header -------------- */\n");
      out.write("header{\n");
      out.write("position: fixed;\n");
      out.write("height : 157px;\n");
      out.write("width: 100%;\n");
      out.write("z-index : 100;\n");
      out.write("background-color : white;\n");
      out.write("top : 0px;\n");
      out.write("}\n");
      out.write("#main-logo{\n");
      out.write("padding: 11px;\n");
      out.write("}\n");
      out.write("#header button {\n");
      out.write("float: right;\n");
      out.write("margin: 1em;\n");
      out.write("width: 6em;\n");
      out.write("height: 2em;\n");
      out.write("border: 1px solid lightgray;\n");
      out.write("font-family: \"InfinitySans-RegularA1\";\n");
      out.write("font-size: 0.7em;\n");
      out.write("color: lightgray;\n");
      out.write("background-color: transparent;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("/* -------------- nav -------------- */\n");
      out.write(".dropdown:hover .dropdown-menu { \n");
      out.write("display: block;\n");
      out.write("margin-top: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#nav{\n");
      out.write("border-top: 1px solid lightgray;\n");
      out.write("border-bottom: 1px solid lightgray;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#nav * {\n");
      out.write("font-family: \"InfinitySans-RegularA1\";\n");
      out.write("text-align: center;\n");
      out.write("vertical-align: middle;\n");
      out.write("border: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#nav a {\n");
      out.write("width: 10rem;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#nav li {\n");
      out.write("width: 10%;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".nav-link {\n");
      out.write("color: #3a3847;\n");
      out.write("width: 100%;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".nav-link:hover {\n");
      out.write("color: #ffce54;\n");
      out.write("border: none;\n");
      out.write("border-bottom: 3px solid !important;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dropdown-menu {\n");
      out.write("border-top: 5px solid transparent !important;\n");
      out.write("width: 10rem;\n");
      out.write("background-color: rgb(250, 250, 250);\n");
      out.write("box-shadow: 0 10px 10px lightgrey;\n");
      out.write("padding-bottom: 20px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dropdown-item {\n");
      out.write("font-size: small;\n");
      out.write("margin-top: 10px;\n");
      out.write("background-color: transparent;\n");
      out.write("opacity: 0.7;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dropdown-item:hover {\n");
      out.write("background-color: #ffce54;\n");
      out.write("color: white;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#userNameArea{\n");
      out.write("\tborder: none !important;\n");
      out.write("\tcolor: #3a3847 !important;\n");
      out.write("}\n");
      out.write("  </style>\n");
      out.write("  \n");
      out.write("  <!--------------------------------- sweet alert ---------------------------------------- -->\n");
      out.write("  <script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\n");
      out.write("  \n");
      out.write("  <script>\n");
      out.write("  ");

 	 String status = (String)(request.getSession().getAttribute("status"));
 	 String msg = (String)(request.getSession().getAttribute("msg"));
 	 String text = (String)(request.getSession().getAttribute("text"));
  
      out.write("\n");
      out.write("  \n");
      out.write("  ");
 if(msg != null){
      out.write("\n");
      out.write("\t\t \t swal({\n");
      out.write("\t\t \t\t icon : \"");
      out.print(status);
      out.write("\", \n");
      out.write("\t\t \t\t title : \"");
      out.print(msg);
      out.write("\",\n");
      out.write("\t\t \t\t text : \"");
      out.print(text != null ? text : "" );
      out.write("\" \n");
      out.write("\t\t \t });\n");
      out.write(" \t ");

 	 		session.removeAttribute("msg");
 	 		session.removeAttribute("status");
 	 		session.removeAttribute("text");
  	}
 	 
      out.write("\n");
      out.write("  \n");
      out.write("  </script>\n");
      out.write("  \n");
      out.write("<body>\n");
      out.write("  <header>\n");
      out.write("    <div class=\"container-fluid\">\n");
      out.write("      <!--  ------------ header ------------ -->\n");
      out.write("      <div class=\"row\" id=\"header\">\n");
      out.write("        <div class=\"col-md-4\">\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-md-4\">\n");
      out.write("          <a href=\"");
      out.print(request.getContextPath());
      out.write("\">\n");
      out.write("            <img src=\"");
      out.print(request.getContextPath());
      out.write("/resources/img/logo_main.png\" width=\"200px\" class=\"mx-auto d-block\" id=\"main-logo\">\n");
      out.write("          </a>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-md-4\">\n");
      out.write("          <button type=\"button\" onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/user/signUpAssign1.do'\">회원가입</button>\n");
      out.write("          \n");
      out.write("          ");
 if(loginUser == null) {
      out.write("\n");
      out.write("          \t <button type=\"button\" onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/userLogin/loginForm.do'\">로그인</button>\n");
      out.write("          ");
 } else{ 
      out.write("\n");
      out.write("          \t <button type=\"button\" onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/userLogin/logout.do'\">로그아웃</button>\n");
      out.write("          \t <button type=\"button\" id=\"userNameArea\" onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/myPage/changeUserForm.do'\">");
      out.print(loginUser.getUserName() );
      out.write(" 님</button>\n");
      out.write("          \t \n");
      out.write("          ");
 } 
      out.write("\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!--  ------------ nav ------------ -->\n");
      out.write("    <div class=\"row\" id=\"nav\">\n");
      out.write("      <div class=\"col-md-12\">\n");
      out.write("        <ul class=\"nav nav-tabs justify-content-center\" id=\"nav-wrapper\">\n");
      out.write("          <li class=\"nav-item dropdown\">\n");
      out.write("            <a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/user/introduce.do\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">구성원 소개</a>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"nav-item dropdown\">\n");
      out.write("            <a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/information/list.do?type=2&category=1\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">정보</a>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"nav-item dropdown\">\n");
      out.write("            <a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/qna/list.do\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">커뮤니티</a>\n");
      out.write("            <div class=\"dropdown-menu\">\n");
      out.write("              <a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath() );
      out.write("/notice/list.do\">공지사항</a>\n");
      out.write("              <a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/qna/list.do\">Q&A</a>\n");
      out.write("              <a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/community/list.do\">자유 게시판</a>\n");
      out.write("              <a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/review/review.do?type=6\">사용 후기</a>\n");
      out.write("            </div>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"nav-item dropdown\">\n");
      out.write("            <a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/event/eventList.do?type=1\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">이벤트</a>\n");
      out.write("            <div class=\"dropdown-menu\">\n");
      out.write("              <a class=\"dropdown-item\"  href=\"");
      out.print(request.getContextPath());
      out.write("/event/eventList.do?type=1\">진행중인 이벤트</a>\n");
      out.write("              <a class=\"dropdown-item\"  href=\"");
      out.print(request.getContextPath());
      out.write("/event/pastList.do?type=2\">종료된 이벤트</a>\n");
      out.write("              <a class=\"dropdown-item\"  href=\"");
      out.print(request.getContextPath());
      out.write("/event/winnerList.do?type=2\">이벤트 당첨자</a>\n");
      out.write("            </div>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"nav-item dropdown\">\n");
      out.write("          \t ");
 if(loginUser != null && loginUser.getUserId().equals("master")){ 
      out.write("\n");
      out.write("          \t \n");
      out.write("          \t\t<a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/masterPage/userAuthList.do\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">관리자 페이지</a>\n");
      out.write("            \n");
      out.write("\t\t\t\t\t\t");
 }else { 
      out.write("\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("            <a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/myPage/changeUserForm.do\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">마이페이지</a>\n");
      out.write("            <div class=\"dropdown-menu\">\n");
      out.write("              <a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/myPage/changeUserForm.do\">회원정보 수정</a>\n");
      out.write("              <a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/myPage/changePwdForm.do\">비밀번호 수정</a>\n");
      out.write("              <a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/myPage/secessionForm.do\">회원 탈퇴</a>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("          </li>\n");
      out.write("        </ul>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </header>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("  <script>\n");
      out.write("    $(function () {\n");
      out.write("      $(\".nav-link\").on(\"mouseenter\", function () {\n");
      out.write("        var idx = $(this).index(\".nav-link\");\n");
      out.write("\n");
      out.write("        $(\".nav-link\").each(function (index, item) {\n");
      out.write("          if (index == idx) {\n");
      out.write("            $(item)\n");
      out.write("              .css(\"color\", \"#ffce54\")\n");
      out.write("              .css(\"border-bottom\", \"3px solid #ffce54\");\n");
      out.write("          } else {\n");
      out.write("            $(item).css(\"color\", \"#3a3847\").css(\"border-bottom\", \"none\");\n");
      out.write("          }\n");
      out.write("        });\n");
      out.write("      });\n");
      out.write("\n");
      out.write("      $(\"#nav\").on(\"mouseleave\", function () {\n");
      out.write("        $(\".nav-link\")\n");
      out.write("          .css(\"color\", \"#3a3847\")\n");
      out.write("          .css(\"border-bottom\", \"3px solid transparent\");\n");
      out.write("      });\n");
      out.write("    });\n");
      out.write("  </script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js\"\n");
      out.write("    integrity=\"sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo\"\n");
      out.write("    crossorigin=\"anonymous\"></script>\n");
      out.write("  <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js\"\n");
      out.write("    integrity=\"sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI\"\n");
      out.write("    crossorigin=\"anonymous\"></script>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("  \t<section id=\"content\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<div id=\"board-area\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- Category -->\r\n");
      out.write("\t\t\t\t");
 String category= null;
				switch(review.getReviewCategory()){
				case 1: category="병원"; break;
				case 2: category="사료"; break;
				case 3: category="간식"; break;
				case 4: category="용품"; break;
				}
      out.write("\r\n");
      out.write("\t\t\t\t<h6 class=\"mt-4\">카테고리 : [");
      out.print(category );
      out.write("]</h6>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- Title -->\r\n");
      out.write("\t\t\t\t<h3 class=\"mt-4\">");
      out.print( review.getReviewTitle() );
      out.write("</h3>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Writer -->\r\n");
      out.write("\t\t\t\t<p class=\"lead\">\r\n");
      out.write("\t\t\t\t\t작성자 : ");
      out.print( review.getUserName());
      out.write("\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<hr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Date -->\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t");
      out.print(review.getReviewCreateDate() );
      out.write("\r\n");
      out.write("\t\t\t \t\t<span class=\"float-right\">조회수 ");
      out.print( review.getReadCount() );
      out.write("</span>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<hr>\r\n");
      out.write("               ");
 if(fList != null){ 
      out.write("\r\n");
      out.write("                <div class=\"carousel slide m-3\" id=\"carousel-325626\">\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"carousel-inner boardImgArea\">\r\n");
      out.write("                     ");
 
                        String src = null;
                        boolean flag = true;
                        for(int i=0; i<3 ; i++) {
                         for(Attachment at : fList){
                          if(at.getFileLevel() == i){
                           src = request.getContextPath()+"/resources/uploadImages/"+at.getFileChangeName();
                           String imgClass = "carousel-item";
                           
                           if(flag){
                            imgClass += " active";
                            flag=false;
                           }
                     
      out.write("     \r\n");
      out.write("                          <div class=\"");
      out.print(imgClass);
      out.write("\">\r\n");
      out.write("                            <img class=\"d-block w-100 boardImg\" src=\"");
      out.print( src );
      out.write("\"/>\r\n");
      out.write("                            <input type=\"hidden\" value=");
      out.print(at.getFileNo() );
      out.write(">\r\n");
      out.write("                           </div> \r\n");
      out.write("                        \r\n");
      out.write("                      ");
  } } } 
      out.write("\r\n");
      out.write("                      \r\n");
      out.write("                    </div> \r\n");
      out.write("                    <a class=\"carousel-control-prev\" href=\"#carousel-325626\" data-slide=\"prev\"><span class=\"carousel-control-prev-icon\"></span> <span class=\"sr-only\">Previous</span></a> <a class=\"carousel-control-next\" href=\"#carousel-325626\" data-slide=\"next\"><span class=\"carousel-control-next-icon\"></span> <span class=\"sr-only\">Next</span></a>\r\n");
      out.write("                </div>\r\n");
      out.write("                ");
 } 
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Content -->\r\n");
      out.write("\t\t\t\t<div id=\"board-content\">");
      out.print( review.getReviewContent() );
      out.write("</div>\r\n");
      out.write("\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t");
 if(loginUser != null && (review.getUserId().equals(loginUser.getUserId()))) {
      out.write("\r\n");
      out.write("\t\t\t\t\t<button id=\"deleteBtn\" class=\"btn btn-primary float-right\" id=\"deleteBtn\">삭제</button>\r\n");
      out.write("\t\t\t\t\t<!--  삭제 버튼 클릭시 해당 게시글 상태를 'N'으로 바꾸고 목록으로 돌아가기 -->\r\n");
      out.write("\t\t\t\t\t<a href=\"updateReview.do?type=");
      out.print(type);
      out.write("&cp=");
      out.print(cp);
      out.write("&no=");
      out.print(review.getReviewBoardNo());
      out.write("\" class=\"btn btn-primary float-right ml-1 mr-1\" id=\"updateBtn\">수정</a>\r\n");
      out.write("\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<a href=\"review.do?type=");
      out.print(type);
      out.write("\" class=\"btn btn-primary float-right\" id=\"listBtn\">목록으로</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("/*댓글*/\r\n");
      out.write("\r\n");
      out.write(".replyWrite>table {\r\n");
      out.write("\twidth: 90%;\r\n");
      out.write("\tmargin-top : 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#replyContentArea {\r\n");
      out.write("\twidth: 90%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#replyContentArea>textarea {\r\n");
      out.write("\tresize: none;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#replyBtnArea {\r\n");
      out.write("\twidth: 100px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".rWriter {\r\n");
      out.write("\tdisplay : inline-block;\r\n");
      out.write("\tmargin-right: 30px;\r\n");
      out.write("\tvertical-align: top;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".rDate {\r\n");
      out.write("\tdisplay : inline-block;\r\n");
      out.write("\tfont-size: 0.5em;\r\n");
      out.write("\tcolor: gray;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#replyListArea {\r\n");
      out.write("\tlist-style-type: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".rContent, .btnArea{\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tbox-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".rContent {\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\twidth : 84.5%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btnArea {\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\twidth : 15%;\r\n");
      out.write("\ttext-align: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<div id=\"reply-area \">\r\n");
      out.write("\r\n");
      out.write("\t<!-- 댓글 작성 부분 -->\r\n");
      out.write("\t<div class=\"replyWrite\">\r\n");
      out.write("\t\t<table align=\"center\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td id=\"replyContentArea\"><textArea rows=\"3\" id=\"replyContent\"></textArea>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td id=\"replyBtnArea\">\r\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-primary\" id=\"addReply\">댓글<br>등록</button>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- 댓글 출력 부분 -->\r\n");
      out.write("\t<div class=\"replyList mt-5 pt-2\">\r\n");
      out.write("\t\t<ul id=\"replyListArea\">\r\n");
      out.write("\t\t\t <li class=\"reply-row\" id=\"1\">\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<p class=\"rWriter\">작성자</p> \r\n");
      out.write("\t\t\t\t\t<p class=\"rDate\">\r\n");
      out.write("\t\t\t\t\t\t작성일  : 2020년 07월 14일 15:12:20<br>\r\n");
      out.write("\t\t\t\t\t\t마지막 수정 날짜 : 2020년 07월 15일 16:17:51\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<p class=\"rContent\">\r\n");
      out.write("\t\t\t\t\tWeb Server Project 댓글 기능 구현중입니다.<br>\r\n");
      out.write("\t\t\t\t\t댓글이 쫌 어려워요 ㅠㅠ\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<div class=\"btnArea\">\r\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-primary\" id=\"updateReply\">수정</button>\r\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-primary\" id=\"deleteReply\">삭제</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<hr> \r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write(" \r\n");
      out.write("<script>\r\n");

	User tempUser = (User)session.getAttribute("loginUser");
	Review tempReview = (Review)request.getAttribute("review");

      out.write("\r\n");
      out.write("\r\n");
      out.write("// 로그인이 되어있는 경우 회원 아이디를 별도 저장해둠.\r\n");
      out.write("var loginUserId;\r\n");
 if(tempUser != null){
      out.write("\r\n");
      out.write("\tloginUserId = \"");
      out.print( tempUser.getUserId());
      out.write("\";\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//-----------------------------------------------------------------------------------------\r\n");
      out.write("// 페이지 로딩 완료 시 댓글 목록 호출\r\n");
      out.write("$(function(){\r\n");
      out.write("\tselectReplyList(");
      out.print(tempReview.getReviewBoardNo());
      out.write(");\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("//-----------------------------------------------------------------------------------------\r\n");
      out.write("// 댓글 목록 불러오기\r\n");
      out.write("function selectReplyList(ReviewBoardNo){\r\n");
      out.write("\tvar url = \"");
      out.print(request.getContextPath());
      out.write("/review/reply/selectList.do\";\r\n");
      out.write("\tconsole.log(ReviewBoardNo);\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl : url,\r\n");
      out.write("\t\tdata : {\"ReviewBoardNo\": ReviewBoardNo},\r\n");
      out.write("\t\tdataType : \"JSON\",\r\n");
      out.write("\t\tsuccess : function(rList){\r\n");
      out.write("\t\t\tconsole.log(rList);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 댓글 목록이 추가되는 영역을 초기화\r\n");
      out.write("\t\t\t$(\"#replyListArea\").html(\"\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.each(rList, function(i){ //i =index \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 댓글 하나를 감싸고 있는 li 태그 생성\r\n");
      out.write("\t\t\tvar $li = $(\"<li>\").addClass(\"reply-row\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 작성자, 작성일, 수정일 영역 div 생성\r\n");
      out.write("\t\t\tvar $div = $(\"<div>\");\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t// 작성자\r\n");
      out.write("\t\t\t\tvar $rWriter = $(\"<a>\").addClass(\"rWriter idSelect\").html(rList[i].userId);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t// 작성일, 수정일\r\n");
      out.write("\t\t\t\tvar $rDate = $(\"<p>\").addClass(\"rDate\")\r\n");
      out.write("\t\t\t\t\t.html(\"작성일 : \" + rList[i].replyCreateDate +\"<br>\"\r\n");
      out.write("\t\t\t\t\t+ \"마지막 수정일 : \" + rList[i].replyModifyDate);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t// 작성자, 작성일, 수정일을 div에 추가하기\r\n");
      out.write("\t\t\t\t$div.append($rWriter, $rDate);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t// 댓글 내용 영역 p태그 생성\r\n");
      out.write("\t\t\tvar $rContent = $(\"<p>\").addClass(\"rContent\").html(rList[i].replyContent);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 댓글 수정, 삭제 버튼 영역\r\n");
      out.write("\t\t\tvar $btnArea = $(\"<div>\").addClass(\"btnArea\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 현재 댓글의 작성자와 로그인한 멤버의 아이디가 같은 경우 버튼을 추가\r\n");
      out.write("\t\t\tif(rList[i].userId == loginUserId){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t// *** 추가되는 버튼에 onclick 이벤트를 부여하여\r\n");
      out.write("\t\t\t\t// 클릭시 수정, 삭제가 되는 함수를 호출하게 만듦.\r\n");
      out.write("\t\t\t\tvar $showUpdate = $(\"<button>\").addClass(\"btn btn-primary btn-sm ml-1\")\r\n");
      out.write("\t\t\t\t\t  .text(\"수정\").attr(\"onclick\", \"showUpdateReply(this, \"+rList[i].replyNo+\")\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\tvar $deleteReply = $(\"<button>\").addClass(\"btn btn-primary btn-sm ml-1\")\r\n");
      out.write("\t\t\t\t  .text(\"삭제\").attr(\"onclick\", \"deleteReply(\"+rList[i].replyNo+\")\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t$btnArea.append($showUpdate, $deleteReply);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 댓글 경계선\r\n");
      out.write("\t\t\tvar $hr = $(\"<hr>\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// li에 $div, $rContent, $btnArea 추가하기\r\n");
      out.write("\t\t\t$li.append($div, $rContent, $btnArea);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 댓글을 화면에 배치\r\n");
      out.write("\t\t\t$(\"#replyListArea\").append($li, $hr);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t}) // for each닫는 괄호\r\n");
      out.write("\t\r\n");
      out.write("\t\t}, error : function(){\r\n");
      out.write("\t\t\tconsole.log(\"ajax 통신 실패\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//-----------------------------------------------------------------------------------------\r\n");
      out.write("// 댓글 등록\r\n");
      out.write("$(\"#addReply\").on(\"click\", function(){\r\n");
      out.write("\t\r\n");
      out.write("\t// 로그인이 되어있는지 확인\r\n");
      out.write("\t");
 if(tempUser == null){
      out.write("\r\n");
      out.write("\t\talert(\"로그인 후 이용해 주세요.\");\r\n");
      out.write("\t");
 }else{
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t // 작성된 댓글 내용을 얻어옴.\r\n");
      out.write("\t var replyContent = $(\"#replyContent\").val();\r\n");
      out.write("\t\r\n");
      out.write("\t // 댓글이 작성 되어 있는지 유효성 검사 진행\r\n");
      out.write("\t if(replyContent.trim().length == 0){\r\n");
      out.write("\t\t alert(\"댓글 작성 후 클릭해주세요.\");\r\n");
      out.write("\t\t $(\"#replyContent\").focus();\r\n");
      out.write("\t }else{\r\n");
      out.write("\t\t // 로그인도 되어있고, 댓글도 작성되어 있는 경우\r\n");
      out.write("\t\t var url = \"");
      out.print( request.getContextPath());
      out.write("/review/reply/insertReply.do\";\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t // 작성자 : loginMemberId 사용 (전역변수)\r\n");
      out.write("\t\t // 글번호 \r\n");
      out.write("\t\t var parentBoardNo = ");
      out.print(tempReview.getReviewBoardNo());
      out.write("; // 숫자로 인식 (문자 인식필요없으므로 쌍따옴표 뺌)\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t $.ajax({\r\n");
      out.write("\t\t\t url : url,\r\n");
      out.write("\t\t\t type : \"post\",\r\n");
      out.write("\t\t\t data : {\"userId\":userId, \r\n");
      out.write("\t\t\t\t\t \"parentBoardNo\":parentBoardNo, \r\n");
      out.write("\t\t\t\t\t \"replyContent\":replyContent},\r\n");
      out.write("\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t success : function(result){\r\n");
      out.write("\t\t\t\t alert(result);\r\n");
      out.write("\t\t\t\t $(\"#replyContent\").val(\"\");\r\n");
      out.write("\t\t\t\t // 삽입된 내용을 화면에서 지움\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t // 갱신된 DB내용을 다시 조회하여 화면 댓글 목록을 갱신함.\r\n");
      out.write("\t\t\t\t selectReplyList(parentBoardNo);\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t }, error : function(){\r\n");
      out.write("\t\t\t\t console.log(\"ajax 통신 실패\");\r\n");
      out.write("\t\t\t }\r\n");
      out.write("\t\t })\r\n");
      out.write("\t }\r\n");
      out.write("\t \r\n");
      out.write("\t");
}
      out.write("\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("//-----------------------------------------------------------------------------------------\r\n");
      out.write("// 댓글 삭제\r\n");
      out.write("\r\n");
      out.write("function deleteReply(replyNo){\r\n");
      out.write("\tif(confirm(\"해당 댓글을 삭제하시겠습니까?\")){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar url = \"");
      out.print(request.getContextPath());
      out.write("/reply/deleteReply.do\";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : url,\r\n");
      out.write("\t\t\tdata : {\"replyNo\" : replyNo},\r\n");
      out.write("\t\t\tsuccess : function(result){\r\n");
      out.write("\t\t\t\tconsole.log(result);\r\n");
      out.write("\t\t\t\talert(result);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t// 댓글 목록 갱신 -> 게시글번호\r\n");
      out.write("\t\t\t\tselectReplyList(");
      out.print(tempReview.getReviewBoardNo());
      out.write(");\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t},error : function(){\r\n");
      out.write("\t\t\t\tconsole.log(\"ajax 통신 실패\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>마이페이지</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("           .footer {\r\n");
      out.write("            background: #ffffff;\r\n");
      out.write("            font-family: \"yg-jalnan\";\r\n");
      out.write("            color: #3a3847;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .footer .col-xs-12{\r\n");
      out.write("            margin-top: 1em;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .footer .contact i {\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            font-family: \"InfinitySans-RegularA1\";\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .footer .copyright p {\r\n");
      out.write("            border-top: 1px solid lightgray;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        .footer img{\r\n");
      out.write("            width: 10em;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .footer p{\r\n");
      out.write("            font-family: \"InfinitySans-RegularA1\";\r\n");
      out.write("            color: #3a3847;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .footer h4{\r\n");
      out.write("            margin-bottom: 0.5em;\r\n");
      out.write("        }\r\n");
      out.write("       \r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <div class=\"footer\">\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("            <div class=\"row mt-5\">\r\n");
      out.write("                <div class=\"col copyright\">\r\n");
      out.write("                    <p></p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row mt-3\">\r\n");
      out.write("            \t<div class=\"col-md-2\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-3\">\r\n");
      out.write("                    <img src=\"");
      out.print(request.getContextPath());
      out.write("/resources/img/logo_footer.png\"\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-3\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-4 contact\">\r\n");
      out.write("                    <h4 class=\"mt-md-0 mt-sm-4\">contact us</h4>\r\n");
      out.write("                    <p>서울특별시 중구 남대문로 120 대일빌딩 2F</p>\r\n");
      out.write("                    <p>1544-9970</p>\r\n");
      out.write("                    <p>info@email.com</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row mt-3\">\r\n");
      out.write("                <div class=\"col copyright\">\r\n");
      out.write("                    <p class=\"\"><small>© 2020. All Rights Reserved.</small></p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js\"\r\n");
      out.write("        integrity=\"sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo\"\r\n");
      out.write("        crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js\"\r\n");
      out.write("        integrity=\"sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI\"\r\n");
      out.write("        crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(\"#deleteBtn\").on(\"click\",function() {\r\n");
      out.write("\t\t\tif(confirm(\"정말 삭제하시겠습니까?\")){\r\n");
      out.write("\t\t\t\tlocation.href=\"delete.do?type=");
      out.print(type);
      out.write("&no=");
      out.print(review.getReviewBoardNo());
      out.write("\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
