/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.56
 * Generated at: 2020-07-28 09:43:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.myPage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kh.banzi.user.model.vo.User;

public final class changeUser_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/views/myPage/../common/header.jsp", Long.valueOf(1595920696662L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.kh.banzi.user.model.vo.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>회원정보 수정</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Required meta tags -->\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\r\n");
      out.write("<!-- Bootstrap CSS -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css\"\r\n");
      out.write("\tintegrity=\"sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk\"\r\n");
      out.write("\tcrossorigin=\"anonymous\" />\r\n");
      out.write("<!-- jQuery -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("#mypage *{\r\n");
      out.write("\tfont-family: \"InfinitySans-RegularA1\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"number\"]::-webkit-outer-spin-button, input[type=\"number\"]::-webkit-inner-spin-button\r\n");
      out.write("\t{\r\n");
      out.write("\t-webkit-appearance: none;\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#title {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#myPage-btn {\r\n");
      out.write("\tfont-family: \"yg-jalnan\" !important;\r\n");
      out.write("\tborder: 10px solid #FFCE54 !important;\r\n");
      out.write("\tbackground-color: #FFCE54;\r\n");
      out.write("\tborder-radius: 0;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#myPage-btn:focus {\r\n");
      out.write("\tbox-shadow: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#myPage-btn:hover {\r\n");
      out.write("\tborder: 10px solid #FFCE54;\r\n");
      out.write("\tbackground-color: #ffffff;\r\n");
      out.write("\tcolor: #FFCE54;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".readonly {\r\n");
      out.write("\tbackground-color: #ffffff !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#mypage input, #mypage select {\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tborder-radius: 0;\r\n");
      out.write("\tborder-bottom: 1px solid #ced4da;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#mypage input:focus, #mypage select:focus {\r\n");
      out.write("\tborder-color: #FFCE54;\r\n");
      out.write("\tbox-shadow: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".readonly:focus {\r\n");
      out.write("\tborder-color: #ced4da !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#mypage fieldset {\r\n");
      out.write("\tborder: 1px solid #ced4da;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#mypage legend {\r\n");
      out.write("\tfont-size: 1.1em;\r\n");
      out.write("\tcolor: #ced4da;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* *************** aside ******************* */\r\n");
      out.write("#myPage-aside *{\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("\tborder-radius: 0;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#myPage-aside li:hover{\r\n");
      out.write("\tbackground-color: #ced4da;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body id=\"mypage\">\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write('\n');
      out.write('\n');
	
	User loginUser = (User)session.getAttribute("loginUser");

	boolean isRemember = false;
	String rememberId = "";
	Cookie[] cookies = request.getCookies();
	
	if(cookies != null){
		for(Cookie c : cookies){
			if("remeberId".equals(c.getName())){
				rememberId = c.getValue();
				isRemember = true;
			}
		}
	}

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("  <meta charset=\"UTF-8\" />\n");
      out.write("\n");
      out.write("  <!-- Required meta tags -->\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\n");
      out.write("  <!-- Bootstrap CSS -->\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css\"\n");
      out.write("    integrity=\"sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk\" crossorigin=\"anonymous\" />\n");
      out.write("  <!-- jQuery -->\n");
      out.write("  <script src=\"https://code.jquery.com/jquery-3.5.1.min.js\"></script>\n");
      out.write("  <title>BAN JI</title>\n");
      out.write("  <style>\n");
      out.write("  \n");
      out.write("/* -------------- body -------------- */\n");
      out.write("\n");
      out.write("* {\n");
      out.write("/* border: 1px solid black; */\n");
      out.write("margin: 0;\n");
      out.write("padding: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".row>div {\n");
      out.write("width: 100%;\n");
      out.write("height: 100%;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* -------------- header -------------- */\n");
      out.write("header{\n");
      out.write("position: fixed;\n");
      out.write("height : 157px;\n");
      out.write("width: 100%;\n");
      out.write("z-index : 100;\n");
      out.write("background-color : white;\n");
      out.write("}\n");
      out.write("#main-logo{\n");
      out.write("padding: 11px;\n");
      out.write("}\n");
      out.write("#header button {\n");
      out.write("float: right;\n");
      out.write("margin: 1em;\n");
      out.write("width: 6em;\n");
      out.write("height: 2em;\n");
      out.write("border: 1px solid lightgray;\n");
      out.write("font-family: \"InfinitySans-RegularA1\";\n");
      out.write("font-size: 0.7em;\n");
      out.write("color: lightgray;\n");
      out.write("background-color: transparent;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("/* -------------- nav -------------- */\n");
      out.write(".dropdown:hover .dropdown-menu { \n");
      out.write("display: block;\n");
      out.write("margin-top: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#nav{\n");
      out.write("border-top: 1px solid lightgray;\n");
      out.write("border-bottom: 1px solid lightgray;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#nav * {\n");
      out.write("font-family: \"InfinitySans-RegularA1\";\n");
      out.write("text-align: center;\n");
      out.write("vertical-align: middle;\n");
      out.write("border: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#nav a {\n");
      out.write("width: 10rem;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#nav li {\n");
      out.write("width: 10%;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".nav-link {\n");
      out.write("color: #3a3847;\n");
      out.write("width: 100%;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".nav-link:hover {\n");
      out.write("color: #ffce54;\n");
      out.write("border: none;\n");
      out.write("border-bottom: 3px solid !important;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dropdown-menu {\n");
      out.write("border-top: 5px solid transparent !important;\n");
      out.write("width: 10rem;\n");
      out.write("background-color: rgb(250, 250, 250);\n");
      out.write("box-shadow: 0 10px 10px lightgrey;\n");
      out.write("padding-bottom: 20px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dropdown-item {\n");
      out.write("font-size: small;\n");
      out.write("margin-top: 10px;\n");
      out.write("background-color: transparent;\n");
      out.write("opacity: 0.7;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dropdown-item:hover {\n");
      out.write("background-color: #ffce54;\n");
      out.write("color: white;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#userNameArea{\n");
      out.write("\tborder: none !important;\n");
      out.write("\tcolor: #3a3847 !important;\n");
      out.write("}\n");
      out.write("  </style>\n");
      out.write("  \n");
      out.write("  <!--------------------------------- sweet alert ---------------------------------------- -->\n");
      out.write("  <script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\n");
      out.write("  \n");
      out.write("  <script>\n");
      out.write("  ");

 	 String status = (String)(request.getSession().getAttribute("status"));
 	 String msg = (String)(request.getSession().getAttribute("msg"));
 	 String text = (String)(request.getSession().getAttribute("text"));
  
      out.write("\n");
      out.write("  \n");
      out.write("  ");
 if(msg != null){
      out.write("\n");
      out.write("\t\t \t swal({\n");
      out.write("\t\t \t\t icon : \"");
      out.print(status);
      out.write("\", \n");
      out.write("\t\t \t\t title : \"");
      out.print(msg);
      out.write("\",\n");
      out.write("\t\t \t\t text : \"");
      out.print(text != null ? text : "" );
      out.write("\" \n");
      out.write("\t\t \t });\n");
      out.write(" \t ");

 	 		session.removeAttribute("msg");
 	 		session.removeAttribute("status");
 	 		session.removeAttribute("text");
  	}
 	 
      out.write("\n");
      out.write("  \n");
      out.write("  </script>\n");
      out.write("  \n");
      out.write("<body>\n");
      out.write("  <header>\n");
      out.write("    <div class=\"container-fluid\">\n");
      out.write("      <!--  ------------ header ------------ -->\n");
      out.write("      <div class=\"row\" id=\"header\">\n");
      out.write("        <div class=\"col-md-4\">\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-md-4\">\n");
      out.write("          <a href=\"");
      out.print(request.getContextPath());
      out.write("\">\n");
      out.write("            <img src=\"");
      out.print(request.getContextPath());
      out.write("/resources/img/logo_main.png\" width=\"200px\" class=\"mx-auto d-block\" id=\"main-logo\">\n");
      out.write("          </a>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-md-4\">\n");
      out.write("          <button type=\"button\" onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/user/signUpAssign1.do'\">회원가입</button>\n");
      out.write("          \n");
      out.write("          ");
 if(loginUser == null) {
      out.write("\n");
      out.write("          \t <button type=\"button\" onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/userLogin/loginForm.do'\">로그인</button>\n");
      out.write("          ");
 } else{ 
      out.write("\n");
      out.write("          \t <button type=\"button\" onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/userLogin/logout.do'\">로그아웃</button>\n");
      out.write("          \t <button type=\"button\" id=\"userNameArea\" onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/myPage/changeUserForm.do'\">");
      out.print(loginUser.getUserName() );
      out.write(" 님</button>\n");
      out.write("          \t \n");
      out.write("          ");
 } 
      out.write("\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!--  ------------ nav ------------ -->\n");
      out.write("    <div class=\"row\" id=\"nav\">\n");
      out.write("      <div class=\"col-md-12\">\n");
      out.write("        <ul class=\"nav nav-tabs justify-content-center\" id=\"nav-wrapper\">\n");
      out.write("          <li class=\"nav-item dropdown\">\n");
      out.write("            <a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/user/introduce.do\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">구성원 소개</a>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"nav-item dropdown\">\n");
      out.write("            <a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/user/introduce.do\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">정보</a>\n");
      out.write("            <div class=\"dropdown-menu\">\n");
      out.write("              <a class=\"dropdown-item\" href=\"#\">음식</a>\n");
      out.write("              <a class=\"dropdown-item\" href=\"#\">견종백과</a>\n");
      out.write("              <a class=\"dropdown-item\" href=\"#\">건강상식</a>\n");
      out.write("              <a class=\"dropdown-item\" href=\"#\">교육/훈련</a>\n");
      out.write("            </div>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"nav-item dropdown\">\n");
      out.write("            <a class=\"nav-link\" href=\"community/list.do\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">커뮤니티</a>\n");
      out.write("            <div class=\"dropdown-menu\">\n");
      out.write("              <a class=\"dropdown-item\" href=\"community/notice.do\">공지사항</a>\n");
      out.write("              <a class=\"dropdown-item\" href=\"community/list.do\">자유 게시판</a>\n");
      out.write("              <a class=\"dropdown-item\" href=\"question\">Q&A</a>\n");
      out.write("              <a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/review/review.do\">사용 후기</a>\n");
      out.write("            </div>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"nav-item dropdown\">\n");
      out.write("            <a class=\"nav-link\" href=\"#\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">이벤트</a>\n");
      out.write("            <div class=\"dropdown-menu\">\n");
      out.write("              <a class=\"dropdown-item\" href=\"#\">진행중인 이벤트</a>\n");
      out.write("              <a class=\"dropdown-item\" href=\"#\">종료된 이벤트</a>\n");
      out.write("            </div>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"nav-item dropdown\">\n");
      out.write("            <a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/myPage/changeUserForm.do\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">마이페이지</a>\n");
      out.write("            <div class=\"dropdown-menu\">\n");
      out.write("              <a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/myPage/changeUserForm.do\">회원정보 수정</a>\n");
      out.write("              <a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/myPage/changePwdForm.do\">비밀번호 수정</a>\n");
      out.write("              <a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/myPage/secessionForm.do\">회원 탈퇴</a>\n");
      out.write("            </div>\n");
      out.write("          </li>\n");
      out.write("        </ul>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </header>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("  <script>\n");
      out.write("    $(function () {\n");
      out.write("      $(\".nav-link\").on(\"mouseenter\", function () {\n");
      out.write("        var idx = $(this).index(\".nav-link\");\n");
      out.write("\n");
      out.write("        $(\".nav-link\").each(function (index, item) {\n");
      out.write("          if (index == idx) {\n");
      out.write("            $(item)\n");
      out.write("              .css(\"color\", \"#ffce54\")\n");
      out.write("              .css(\"border-bottom\", \"3px solid #ffce54\");\n");
      out.write("          } else {\n");
      out.write("            $(item).css(\"color\", \"#3a3847\").css(\"border-bottom\", \"none\");\n");
      out.write("          }\n");
      out.write("        });\n");
      out.write("      });\n");
      out.write("\n");
      out.write("      $(\"#nav\").on(\"mouseleave\", function () {\n");
      out.write("        $(\".nav-link\")\n");
      out.write("          .css(\"color\", \"#3a3847\")\n");
      out.write("          .css(\"border-bottom\", \"3px solid transparent\");\n");
      out.write("      });\n");
      out.write("    });\n");
      out.write("  </script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js\"\n");
      out.write("    integrity=\"sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo\"\n");
      out.write("    crossorigin=\"anonymous\"></script>\n");
      out.write("  <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js\"\n");
      out.write("    integrity=\"sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI\"\n");
      out.write("    crossorigin=\"anonymous\"></script>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<section id=\"content\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t<div class=\"container-fluid mt-5\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t\t\t<h3 id=\"title\">회원정보 수정</h3>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-10 mt-5 mx-auto\" id=\"myPage-aside\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"list-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"list-group-item list-group-item-action\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/myPage/changeUserForm.do\">회원정보 수정</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"list-group-item list-group-item-action\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/myPage/changePwdForm.do\">비밀번호 수정</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"list-group-item list-group-item-action\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/myPage/secessionForm.do\">회원 탈퇴</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"col-md-9\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"bg-white shadow-sm container p-5\">\r\n");
      out.write("\t\t\t\t\t\t\t<form method=\"POST\" action=\"changeUser.do\" onsubmit=\"return validate();\" class=\"form-horizontal\"\r\n");
      out.write("\t\t\t\t\t\t\t\trole=\"form\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- 아이디 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row mb-5 ml-3 mr-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control readonly\" id=\"id\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tname=\"id\" value=\"");
      out.print(loginUser.getUserId());
      out.write("\" readonly>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- 이름 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row mb-5 ml-3 mr-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control readonly\" id=\"name\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tname=\"name\" value=\"");
      out.print(loginUser.getUserName());
      out.write("\" readonly>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- 보안질문 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row mb-5 ml-4 mr-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<fieldset class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<legend class=\"col-md-3 mb-4\">보안질문</legend>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-12 mb-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<select class=\"custom-select input\" id=\"question\" name=\"question\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"first\">내 학창시절 별명은?</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"second\">가장 좋아했던 동화책의 제목은?</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"third\">첫 애완동물의 이름은?</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-12 mb-5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control input\" id=\"answer\" name=\"answer\" value=\"");
      out.print(loginUser.getUserAnswer());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$.each($(\"#question > option\"), function(index, item){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tif($(item).val() == \"");
      out.print(loginUser.getUserQuestion());
      out.write("\"){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t$(item).prop(\"selected\",true);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t</script>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- 이메일 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row mb-5 ml-3 mr-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"email\" class=\"form-control input\" id=\"email\" name=\"email\" value=\"");
      out.print(loginUser.getUserEmail());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- 등급 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row mb-5 ml-4 mr-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<fieldset class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<legend class=\"col-md-3 mb-4\">등급</legend>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t&nbsp;<input type=\"radio\" id=\"user\" name=\"grade\" value=\"user\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"user\">사용자</label>&nbsp;&nbsp;&nbsp; \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t&nbsp;<input type=\"radio\" id=\"veterinarian\" name=\"grade\" value=\"veterinarian\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"veterinarian\">수의사</label>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t&nbsp;<input type=\"radio\" id=\"trainer\" name=\"grade\"value=\"trainer\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"trainer\">훈련사</label> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t&nbsp;<input type=\"radio\" id=\"editor\" name=\"grade\" value=\"editor\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"editor\">에디터</label>&nbsp;&nbsp;&nbsp; \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<br><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(function(){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(\"input:radio[value='");
      out.print(loginUser.getUserGrade());
      out.write("']\").prop(\"checked\", true);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row mb-5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button class=\"btn btn-primary btn-lg btn-block\" type=\"submit\" id=\"myPage-btn\">수정</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tfunction validate() {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif($(\"#answer\").val().trim() == \"\"){\r\n");
      out.write("\t\t\t\talert(\"보안 질문에 답변해주세요.\");\r\n");
      out.write("\t\t\t\t$(\"#answer\").focus();\r\n");
      out.write("\t\t\t\treturn false; \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif($(\"#email\").val().trim() == \"\"){\r\n");
      out.write("\t\t\t\talert(\"이메일을 입력해주세요.\");\r\n");
      out.write("\t\t\t\t$(\"#email\").focus();\r\n");
      out.write("\t\t\t\treturn false; \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\treturn true;\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
