/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.56
 * Generated at: 2020-08-05 07:23:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.community;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.SimpleDateFormat;
import com.kh.banzi.common.Attachment;
import com.kh.banzi.community.model.vo.Community;
import java.util.ArrayList;
import com.kh.banzi.user.model.vo.User;

public final class communityView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/community/../common/header.jsp", Long.valueOf(1596610595358L));
    _jspx_dependants.put("/WEB-INF/views/community/../common/footer.jsp", Long.valueOf(1595989111466L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.kh.banzi.common.Attachment");
    _jspx_imports_classes.add("com.kh.banzi.community.model.vo.Community");
    _jspx_imports_classes.add("com.kh.banzi.user.model.vo.User");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
 
  ArrayList<Attachment> fList = (ArrayList<Attachment>)request.getAttribute("fList");
  Community community = (Community)request.getAttribute("community");
	String cp = request.getParameter("cp");
	String pattern = "yy-MM-dd HH:mm";
	SimpleDateFormat sdf1 = new SimpleDateFormat(pattern);

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Nanum+Gothic&display=swap\" rel=\"stylesheet\">\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>게시글</title>\n");
      out.write("<style>\n");
      out.write("\t#board-area{ margin-bottom:100px;}\n");
      out.write("\t#board-content{ padding-bottom:150px;}\n");
      out.write("\n");
      out.write("\t.boardImgArea{\n");
      out.write("\t\theight: 300px;\n");
      out.write("\t}\n");
      out.write("\t*{\n");
      out.write("\tfont-family: 'Nanum Gothic', sans-serif;\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\t.boardImg{\n");
      out.write("\t\twidth : 100%;\n");
      out.write("\t\theight: 100%;\n");
      out.write("\t\t\n");
      out.write("\t\tmax-width : 300px;\n");
      out.write("\t\tmax-height: 300px;\n");
      out.write("\t\t\n");
      out.write("\t\tmargin : auto;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t/* 이미지 화살표 색 조정\n");
      out.write("\t-> fill='%23000' 부분의 000을\n");
      out.write("\t   RGB 16진수 값을 작성하여 변경 가능 \n");
      out.write("\t */\n");
      out.write("\t.carousel-control-prev-icon {\n");
      out.write(" \t\tbackground-image: url(\"data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' fill='%23000' viewBox='0 0 8 8'%3E%3Cpath d='M5.25 0l-4 4 4 4 1.5-1.5-2.5-2.5 2.5-2.5-1.5-1.5z'/%3E%3C/svg%3E\") !important;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t.carousel-control-next-icon {\n");
      out.write("  \t\tbackground-image: url(\"data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' fill='%23000' viewBox='0 0 8 8'%3E%3Cpath d='M2.75 0l-1.5 1.5 2.5 2.5-2.5 2.5 1.5 1.5 4-4-4-4z'/%3E%3C/svg%3E\") !important;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t.replyWrite > table{\n");
      out.write("\t\twidth: 100%;\n");
      out.write("\t\talign: center;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t#replyContentArea{ width: 90%; }\n");
      out.write("\t\n");
      out.write("\t#replyContentArea > textarea{\n");
      out.write("\t    resize: none;\n");
      out.write("    \twidth: 100%;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t#replyBtnArea{\n");
      out.write("\t    width: 100px;\n");
      out.write("\t    text-align: center;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t.rWriter{ margin-right: 30px;}\n");
      out.write("\t.rDate{\n");
      out.write("\t\tfont-size: 0.7em;\n");
      out.write("\t\tcolor : gray;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t#replyListArea{\n");
      out.write("\t\tlist-style-type: none;\n");
      out.write("\t}\n");
      out.write("\t.container{\n");
      out.write("\t  padding-top:157px;\n");
      out.write("\t}\n");
      out.write("\t.reply_content{\n");
      out.write("\t width:80%;\n");
      out.write("\t}\n");
      out.write("\t.p1{\n");
      out.write("\t font-size:1.2em;\n");
      out.write("\t font-weight:bold;\n");
      out.write("\t}\n");
      out.write("\t.hr{\n");
      out.write("    border-top:2px solid #868484;\n");
      out.write("\t}\n");
      out.write("\t.rWriter{\n");
      out.write("\t padding-bottom: 15px;\n");
      out.write("   font-weight: 600;\n");
      out.write("   font-size:0.9em;\n");
      out.write("\t}\n");
      out.write("\t.reply_content{\n");
      out.write("\t margin:20px 0px 25px;\n");
      out.write("\t}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t\t");
      out.write('\n');
      out.write('\n');
	
	User loginUser = (User)session.getAttribute("loginUser");

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("  <meta charset=\"UTF-8\" />\n");
      out.write("\n");
      out.write("  <!-- Required meta tags -->\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\n");
      out.write("  <!-- Bootstrap CSS -->\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css\"\n");
      out.write("    integrity=\"sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk\" crossorigin=\"anonymous\" />\n");
      out.write("  <!-- jQuery -->\n");
      out.write("  <script src=\"https://code.jquery.com/jquery-3.5.1.min.js\"></script>\n");
      out.write("\n");
      out.write("    <!-- CSS -->\n");
      out.write("   <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/style.css\">\n");
      out.write("\n");
      out.write("  <title>BAN JI</title>\n");
      out.write("  <style>\n");
      out.write("  \n");
      out.write("/* -------------- body -------------- */\n");
      out.write("\n");
      out.write("* {\n");
      out.write("/* border: 1px solid black; */\n");
      out.write("margin: 0;\n");
      out.write("padding: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".row>div {\n");
      out.write("width: 100%;\n");
      out.write("height: 100%;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* -------------- header -------------- */\n");
      out.write("header{\n");
      out.write("position: fixed;\n");
      out.write("height : 157px;\n");
      out.write("width: 100%;\n");
      out.write("z-index : 100;\n");
      out.write("background-color : white;\n");
      out.write("top : 0px;\n");
      out.write("}\n");
      out.write("#main-logo{\n");
      out.write("padding: 11px;\n");
      out.write("}\n");
      out.write("#header button {\n");
      out.write("float: right;\n");
      out.write("margin: 1em;\n");
      out.write("width: 6em;\n");
      out.write("height: 2em;\n");
      out.write("border: 1px solid lightgray;\n");
      out.write("font-family: \"InfinitySans-RegularA1\";\n");
      out.write("font-size: 0.7em;\n");
      out.write("color: lightgray;\n");
      out.write("background-color: transparent;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("/* -------------- nav -------------- */\n");
      out.write(".dropdown:hover .dropdown-menu { \n");
      out.write("display: block;\n");
      out.write("margin-top: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#nav{\n");
      out.write("border-top: 1px solid lightgray;\n");
      out.write("border-bottom: 1px solid lightgray;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#nav * {\n");
      out.write("font-family: \"InfinitySans-RegularA1\";\n");
      out.write("text-align: center;\n");
      out.write("vertical-align: middle;\n");
      out.write("border: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#nav a {\n");
      out.write("width: 10rem;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#nav li {\n");
      out.write("width: 10%;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".nav-link {\n");
      out.write("color: #3a3847;\n");
      out.write("width: 100%;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".nav-link:hover {\n");
      out.write("color: #ffce54;\n");
      out.write("border: none;\n");
      out.write("border-bottom: 3px solid !important;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dropdown-menu {\n");
      out.write("border-top: 5px solid transparent !important;\n");
      out.write("width: 10rem;\n");
      out.write("background-color: rgb(250, 250, 250);\n");
      out.write("box-shadow: 0 10px 10px lightgrey;\n");
      out.write("padding-bottom: 20px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dropdown-item {\n");
      out.write("font-size: small;\n");
      out.write("margin-top: 10px;\n");
      out.write("background-color: transparent;\n");
      out.write("opacity: 0.7;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dropdown-item:hover {\n");
      out.write("background-color: #ffce54;\n");
      out.write("color: white;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#userNameArea{\n");
      out.write("\tborder: none !important;\n");
      out.write("\tcolor: #3a3847 !important;\n");
      out.write("}\n");
      out.write("  </style>\n");
      out.write("  \n");
      out.write("  <!--------------------------------- sweet alert ---------------------------------------- -->\n");
      out.write("  <script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\n");
      out.write("  \n");
      out.write("  <script>\n");
      out.write("  ");

 	 String status = (String)(request.getSession().getAttribute("status"));
 	 String msg = (String)(request.getSession().getAttribute("msg"));
 	 String text = (String)(request.getSession().getAttribute("text"));
  
      out.write("\n");
      out.write("  \n");
      out.write("  ");
 if(msg != null){
      out.write("\n");
      out.write("\t\t \t swal({\n");
      out.write("\t\t \t\t icon : \"");
      out.print(status);
      out.write("\", \n");
      out.write("\t\t \t\t title : \"");
      out.print(msg);
      out.write("\",\n");
      out.write("\t\t \t\t text : \"");
      out.print(text != null ? text : "" );
      out.write("\" \n");
      out.write("\t\t \t });\n");
      out.write(" \t ");

 	 		session.removeAttribute("msg");
 	 		session.removeAttribute("status");
 	 		session.removeAttribute("text");
  	}
 	 
      out.write("\n");
      out.write("  \n");
      out.write("  </script>\n");
      out.write("  \n");
      out.write("<body>\n");
      out.write("  <header>\n");
      out.write("    <div class=\"container-fluid\">\n");
      out.write("      <!--  ------------ header ------------ -->\n");
      out.write("      <div class=\"row\" id=\"header\">\n");
      out.write("        <div class=\"col-md-4\">\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-md-4\">\n");
      out.write("          <a href=\"");
      out.print(request.getContextPath());
      out.write("\">\n");
      out.write("            <img src=\"");
      out.print(request.getContextPath());
      out.write("/resources/img/logo_main.png\" width=\"200px\" class=\"mx-auto d-block\" id=\"main-logo\">\n");
      out.write("          </a>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-md-4\">\n");
      out.write("          <button type=\"button\" onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/user/signUpAssign1.do'\">회원가입</button>\n");
      out.write("          \n");
      out.write("          ");
 if(loginUser == null) {
      out.write("\n");
      out.write("          \t <button type=\"button\" onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/userLogin/loginForm.do'\">로그인</button>\n");
      out.write("          ");
 } else{ 
      out.write("\n");
      out.write("          \t <button type=\"button\" onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/userLogin/logout.do'\">로그아웃</button>\n");
      out.write("          \t <button type=\"button\" id=\"userNameArea\" onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/myPage/changeUserForm.do'\">");
      out.print(loginUser.getUserName() );
      out.write(" 님</button>\n");
      out.write("          \t \n");
      out.write("          ");
 } 
      out.write("\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!--  ------------ nav ------------ -->\n");
      out.write("    <div class=\"row\" id=\"nav\">\n");
      out.write("      <div class=\"col-md-12\">\n");
      out.write("        <ul class=\"nav nav-tabs justify-content-center\" id=\"nav-wrapper\">\n");
      out.write("          <li class=\"nav-item dropdown\">\n");
      out.write("            <a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/user/introduce.do\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">구성원 소개</a>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"nav-item dropdown\">\n");
      out.write("            <a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/information/list.do?type=2&category=1\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">정보</a>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"nav-item dropdown\">\n");
      out.write("            <a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/qna/list.do\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">커뮤니티</a>\n");
      out.write("            <div class=\"dropdown-menu\">\n");
      out.write("              <a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath() );
      out.write("/notice/list.do\">공지사항</a>\n");
      out.write("              <a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/qna/list.do\">Q&A</a>\n");
      out.write("              <a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/community/list.do\">자유 게시판</a>\n");
      out.write("              <a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/review/review.do?type=6\">사용 후기</a>\n");
      out.write("            </div>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"nav-item dropdown\">\n");
      out.write("            <a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/event/eventList.do?type=1\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">이벤트</a>\n");
      out.write("            <div class=\"dropdown-menu\">\n");
      out.write("              <a class=\"dropdown-item\"  href=\"");
      out.print(request.getContextPath());
      out.write("/event/eventList.do?type=1\">진행중인 이벤트</a>\n");
      out.write("              <a class=\"dropdown-item\"  href=\"");
      out.print(request.getContextPath());
      out.write("/event/pastList.do?type=2\">종료된 이벤트</a>\n");
      out.write("              <a class=\"dropdown-item\"  href=\"");
      out.print(request.getContextPath());
      out.write("/event/winnerList.do?type=2\">이벤트 당첨자</a>\n");
      out.write("            </div>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"nav-item dropdown\">\n");
      out.write("          \t ");
 if(loginUser != null && loginUser.getUserId().equals("master")){ 
      out.write("\n");
      out.write("          \t \n");
      out.write("          \t\t<a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/masterPage/userAuthList.do\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">관리자 페이지</a>\n");
      out.write("            \n");
      out.write("\t\t\t\t\t\t");
 }else { 
      out.write("\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("            <a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/myPage/changeUserForm.do\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">마이페이지</a>\n");
      out.write("            <div class=\"dropdown-menu\">\n");
      out.write("              <a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/myPage/changeUserForm.do\">회원정보 수정</a>\n");
      out.write("              <a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/myPage/changePwdForm.do\">비밀번호 수정</a>\n");
      out.write("              <a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/myPage/secessionForm.do\">회원 탈퇴</a>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("          </li>\n");
      out.write("        </ul>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </header>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("  <script>\n");
      out.write("    $(function () {\n");
      out.write("      $(\".nav-link\").on(\"mouseenter\", function () {\n");
      out.write("        var idx = $(this).index(\".nav-link\");\n");
      out.write("\n");
      out.write("        $(\".nav-link\").each(function (index, item) {\n");
      out.write("          if (index == idx) {\n");
      out.write("            $(item)\n");
      out.write("              .css(\"color\", \"#ffce54\")\n");
      out.write("              .css(\"border-bottom\", \"3px solid #ffce54\");\n");
      out.write("          } else {\n");
      out.write("            $(item).css(\"color\", \"#3a3847\").css(\"border-bottom\", \"none\");\n");
      out.write("          }\n");
      out.write("        });\n");
      out.write("      });\n");
      out.write("\n");
      out.write("      $(\"#nav\").on(\"mouseleave\", function () {\n");
      out.write("        $(\".nav-link\")\n");
      out.write("          .css(\"color\", \"#3a3847\")\n");
      out.write("          .css(\"border-bottom\", \"3px solid transparent\");\n");
      out.write("      });\n");
      out.write("    });\n");
      out.write("  </script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js\"\n");
      out.write("    integrity=\"sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo\"\n");
      out.write("    crossorigin=\"anonymous\"></script>\n");
      out.write("  <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js\"\n");
      out.write("    integrity=\"sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI\"\n");
      out.write("    crossorigin=\"anonymous\"></script>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
      out.write("\n");
      out.write("\t<div class=\"container\">\n");
      out.write("\n");
      out.write("\t\t<div>\n");
      out.write("\n");
      out.write("\t\t\t<div id=\"board-area\">\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Title -->\n");
      out.write("\t\t\t\t<h3 class=\"mt-4\">");
      out.print( community.getTitle() );
      out.write("</h3>\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Writer -->\n");
      out.write("\t\t\t\t<p class=\"lead\">\n");
      out.write("\t\t\t\t\t작성자 : ");
      out.print( community.getRegName() );
      out.write("\n");
      out.write("\t\t\t\t</p>\n");
      out.write("\n");
      out.write("\t\t\t\t<hr>\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Date -->\n");
      out.write("\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t");
      out.print( sdf1.format(community.getRegDate()) );
      out.write("\n");
      out.write("\t\t\t \t\t<span class=\"float-right\">조회수 ");
      out.print( community.getViews() );
      out.write("</span>\n");
      out.write("\t\t\t\t</p>\n");
      out.write("\n");
      out.write("\t\t\t\t<hr>\n");
      out.write("               ");
 if(fList != null){ 
      out.write("\n");
      out.write("                <div class=\"carousel slide m-3\" id=\"carousel-325626\">\n");
      out.write("                    \n");
      out.write("                    <div class=\"carousel-inner boardImgArea\">\n");
      out.write("                     ");
 
                        String src = null;
                        boolean flag = true;
                        for(int i=0; i<4 ; i++) {
                         for(Attachment at : fList){
                          if(at.getFileLevel() == i){
                           src = request.getContextPath()+"/resources/uploadImages/"+at.getFileChangeName();
                           String imgClass = "carousel-item";
                           
                           if(flag){
                            imgClass += " active";
                            flag=false;
                           }
                     
      out.write("     \n");
      out.write("                          <div class=\"");
      out.print(imgClass);
      out.write("\">\n");
      out.write("                            <img class=\"d-block w-100 boardImg\" src=\"");
      out.print( src );
      out.write("\"/>\n");
      out.write("                            <input type=\"hidden\" value=");
      out.print(at.getFileNo() );
      out.write(">\n");
      out.write("                           </div> \n");
      out.write("                        \n");
      out.write("                      ");
  } } } 
      out.write("\n");
      out.write("                      \n");
      out.write("                    </div> \n");
      out.write("                    <a class=\"carousel-control-prev\" href=\"#carousel-325626\" data-slide=\"prev\"><span class=\"carousel-control-prev-icon\"></span> <span class=\"sr-only\">Previous</span></a> <a class=\"carousel-control-next\" href=\"#carousel-325626\" data-slide=\"next\"><span class=\"carousel-control-next-icon\"></span> <span class=\"sr-only\">Next</span></a>\n");
      out.write("                </div>\n");
      out.write("                ");
 } 
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Content -->\n");
      out.write("\t\t\t\t<div id=\"board-content\">");
      out.print( community.getContent() );
      out.write("</div>\n");
      out.write("\t\t\t\t<div id=\"reply-area \">\n");
      out.write("\t\t\t\t  ");
if(loginUser != null) {
      out.write("\n");
      out.write("\t\t\t\t  <!-- 댓글 작성 부분 -->\n");
      out.write("\t\t\t\t  <div class=\"replyWrite\">\n");
      out.write("\t\t\t\t    <table align=\"center\">\n");
      out.write("\t\t\t\t      <tr>\n");
      out.write("\t\t\t\t        <td id=\"replyContentArea\"><textArea rows=\"3\" id=\"replyContent\"></textArea>\n");
      out.write("\t\t\t\t        </td>\n");
      out.write("\t\t\t\t        <td id=\"replyBtnArea\">\n");
      out.write("\t\t\t\t          <button class=\"btn btn-primary\" id=\"addReply\">댓글<br>등록</button>\n");
      out.write("\t\t\t\t        </td>\n");
      out.write("\t\t\t\t      </tr>\n");
      out.write("\t\t\t\t    </table>\n");
      out.write("\t\t\t\t  </div>\n");
      out.write("\t\t\t\t");
} 
      out.write("\n");
      out.write("\t\t\t\t  <!-- 댓글 출력 부분 -->\n");
      out.write("\t\t\t\t  <div class =\"relply-list\">\n");
      out.write("\t\t\t\t  </div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t<hr>\n");
      out.write("\t\t\t\t \n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<div>\n");
      out.write(" \t\t\t\t\t");
 if(loginUser != null && (community.getRegName().equals(loginUser.getUserName()))) {
      out.write("\n");
      out.write("\t\t\t  <button id=\"deleteBtn\" class=\"btn btn-primary float-right\">삭제</button>\n");
      out.write("\t\t\t\t\t<!-- 삭제 버튼 클릭시 해당 게시글 상태를 'N'으로 바꾸고 목록으로 돌아가기 --> \n");
      out.write("\t\t\t\t\t<a href=\"updateForm.do?cp=");
      out.print(cp);
      out.write("&no=");
      out.print(community.getBoardNo());
      out.write("\" class=\"btn btn-primary float-right ml-1 mr-1\">수정</a>\n");
      out.write("\t\t\t\t\t");
 } 
      out.write(" \n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<a href=\"list.do?cp=");
      out.print(cp);
      out.write("\" class=\"btn btn-primary float-right\">목록으로</a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>마이페이지</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("           .footer {\r\n");
      out.write("            background: #ffffff;\r\n");
      out.write("            font-family: \"yg-jalnan\";\r\n");
      out.write("            color: #3a3847;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .footer .col-xs-12{\r\n");
      out.write("            margin-top: 1em;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .footer .contact i {\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            font-family: \"InfinitySans-RegularA1\";\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .footer .copyright p {\r\n");
      out.write("            border-top: 1px solid lightgray;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        .footer img{\r\n");
      out.write("            width: 10em;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .footer p{\r\n");
      out.write("            font-family: \"InfinitySans-RegularA1\";\r\n");
      out.write("            color: #3a3847;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .footer h4{\r\n");
      out.write("            margin-bottom: 0.5em;\r\n");
      out.write("        }\r\n");
      out.write("       \r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <div class=\"footer\">\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("            <div class=\"row mt-5\">\r\n");
      out.write("                <div class=\"col copyright\">\r\n");
      out.write("                    <p></p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row mt-3\">\r\n");
      out.write("            \t<div class=\"col-md-2\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-3\">\r\n");
      out.write("                    <img src=\"");
      out.print(request.getContextPath());
      out.write("/resources/img/logo_footer.png\"\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-3\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-4 contact\">\r\n");
      out.write("                    <h4 class=\"mt-md-0 mt-sm-4\">contact us</h4>\r\n");
      out.write("                    <p>서울특별시 중구 남대문로 120 대일빌딩 2F</p>\r\n");
      out.write("                    <p>1544-9970</p>\r\n");
      out.write("                    <p>info@email.com</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row mt-3\">\r\n");
      out.write("                <div class=\"col copyright\">\r\n");
      out.write("                    <p class=\"\"><small>© 2020. All Rights Reserved.</small></p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js\"\r\n");
      out.write("        integrity=\"sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo\"\r\n");
      out.write("        crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js\"\r\n");
      out.write("        integrity=\"sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI\"\r\n");
      out.write("        crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("\t<script>\n");
      out.write(" ");
      out.write('\n');
      out.write('	');
      out.write(' ');

	    User tempUser = (User)session.getAttribute("loginUser");
	
      out.write("\n");
      out.write("\tvar loginMemberId;\n");
      out.write("\t");
 if(tempUser != null){
      out.write("\n");
      out.write("\tuserId = \"");
      out.print(tempUser.getUserId());
      out.write("\";\n");
      out.write("\tuserNick = \"");
      out.print(tempUser.getUserName());
      out.write("\";\n");
      out.write("\t");
} else {
      out.write("\n");
      out.write("\tuserNick = \"\";\n");
      out.write("\t");
}
      out.write("\n");
      out.write(" \t    $(function(){\n");
      out.write(" \t\t     selectReplyList(");
      out.print(community.getBoardNo());
      out.write(");\n");
      out.write(" \t\t   });\n");
      out.write(" \t\t   \n");
      out.write(" \t    // 댓글 목록 조회\n");
      out.write("\t   function selectReplyList(boardNo){\n");
      out.write("\t     var url = \"");
      out.print( request.getContextPath() );
      out.write("/qna/selectReply.do\";\n");
      out.write("\t     $.ajax({\n");
      out.write("\t       url : url,\n");
      out.write("\t       data : {\"boardNo\" : boardNo},\n");
      out.write("\t       dataType : \"JSON\",\n");
      out.write("\t       success : function(rList){\n");
      out.write("\t         if(rList.length != 0){\n");
      out.write("\t        \t   $(\".relply-list\").html(\"\");\n");
      out.write("\t             $hr = $(\"<hr>\").addClass(\"hr\");\n");
      out.write("\t             $p1 = $(\"<p>\").addClass(\"p1\").text(\"댓글\");\n");
      out.write("\t             $(\".relply-list\").append($hr,$p1);\n");
      out.write("\t             for(var i = 0; i < rList.length; i++){\n");
      out.write("\t               if(i > 0){\n");
      out.write("\t            \t   $hr2 = $(\"<hr>\");\n");
      out.write("\t                 $(\".relply-list\").append($hr2); \n");
      out.write("\t               }\n");
      out.write("\t               $div = $(\"<div>\").addClass(\"rWriter\").html(\"작성자 : \" + rList[i].regWriter +\"<br>\"+\"작성일 : \" + rList[i].regDate);\n");
      out.write("\t               $p2 = $(\"<p>\").addClass(\"reply_content\").html(rList[i].content);\n");
      out.write("\t               $(\".relply-list\").append($div, $p2);\n");
      out.write("\t               if(userNick == rList[i].regWriter){\n");
      out.write("\t            \t   var $deleteReply = $(\"<button>\").addClass(\"btn btn-primary btn-sm ml-1\").text(\"삭제\").attr(\"onclick\",\"showDeleteReply(\"+rList[i].replyNo+\")\");\n");
      out.write("\t            \t   $(\".relply-list\").append( $deleteReply);  \n");
      out.write("\t               }\n");
      out.write("\t             }\n");
      out.write("\t           \n");
      out.write("\t         }\n");
      out.write("\t       }, error : function() {\n");
      out.write("\t         console.log(\"ajax 통신 실패\");\n");
      out.write("\t       }\n");
      out.write("\t     });\n");
      out.write("\t   }\n");
      out.write(" \t\t   \n");
      out.write(" \t\t   \n");
      out.write(" \t\t   $(\"#addReply\").on(\"click\",function(){\n");
      out.write(" \t\t\t   var content = $(\"#replyContent\").val();\n");
      out.write(" \t\t\t   \n");
      out.write(" \t\t\t   if(content.trim().length==0){\n");
      out.write(" \t\t\t\t   alert(\"댓글 작성 후 클릭해 주세요\");\n");
      out.write("\t\t\t     $(\"#replyContent\").focus();\n");
      out.write(" \t\t\t   }else{\n");
      out.write(" \t\t\t\t   var url = \"");
      out.print(request.getContextPath());
      out.write("/community/insertReply.do\";\n");
      out.write(" \t\t\t\t   var boardNo = \"");
      out.print(community.getBoardNo());
      out.write("\";\n");
      out.write(" \t\t\t\t   var regName = \"");
      out.print(community.getRegName());
      out.write("\";\n");
      out.write("\t\t\t     $.ajax({\n");
      out.write("\t\t\t        url : url,\n");
      out.write("\t\t\t        type : \"POST\",\n");
      out.write("\t\t\t        data : {\"regName\" : regName, \"boardNo\" : boardNo, \"content\" : content},\n");
      out.write("\t\t\t        \n");
      out.write("\t\t\t        success : function(result){\n");
      out.write("\t\t\t          alert(result);\n");
      out.write("\t\t\t          $(\"#replyContent\").val(\"\");\n");
      out.write("\t\t\t          // 삽입된 내용을 화면에서 지움\n");
      out.write("\t\t\t          \n");
      out.write("\t\t\t          // 갱신된 DB 내용을 다시 조회하여 화면 댓글 목록을 갱신함.\n");
      out.write("\t\t\t          selectReplyList(boardNo);\n");
      out.write("\t\t\t        }, error : function(){\n");
      out.write("\t\t\t          console.log(\"ajax 통신 실패\");\n");
      out.write("\t\t\t        }\n");
      out.write("\t\t\t      });\n");
      out.write(" \t\t\t   }\n");
      out.write(" \t\t   });\n");
      out.write(" \t\t   \n");
      out.write(" \t\t    function showDeleteReply(replyNo){\n");
      out.write(" \t\t      if(confirm(\"해당 댓글을 삭제하시겠습니까?\")){\n");
      out.write(" \t\t      /*  var boardNo = $(\"[type='hidden']\").attr(\"class\") */;\n");
      out.write(" \t\t      var boardNo = \"");
      out.print(community.getBoardNo());
      out.write("\";\n");
      out.write(" \t\t       $.ajax({\n");
      out.write(" \t\t    \t  url : \"");
      out.print(request.getContextPath());
      out.write("/community/deleteReply.do\",\n");
      out.write(" \t\t        data : {\"replyNo\" : replyNo},\n");
      out.write(" \t\t        success : function(result){\n");
      out.write(" \t\t          alert(result);\n");
      out.write("              selectReplyList(boardNo);\n");
      out.write(" \t\t        }, error :  function(){\n");
      out.write(" \t\t          console.log(\"ajax 통신 실패\");\n");
      out.write(" \t\t        }\n");
      out.write(" \t\t         \n");
      out.write(" \t\t       });\n");
      out.write(" \t\t      }else{\n");
      out.write(" \t\t    \t  return;\n");
      out.write(" \t\t      }      \n");
      out.write(" \t\t     };\n");
      out.write(" \t\t     \n");
      out.write(" \t\t     // 글삭제\n");
      out.write(" \t\t    $(\"#deleteBtn\").on(\"click\",function(){\n");
      out.write("          if(confirm(\"해당 글을삭제하시겠습니까?\")){\n");
      out.write("        \t  var boardNo = \"");
      out.print(community.getBoardNo());
      out.write("\";\n");
      out.write("        \t  location.href =\"");
      out.print(request.getContextPath());
      out.write("/community/delete.do?no=\"+boardNo;\n");
      out.write("          }else{\n");
      out.write("        \t  return;\n");
      out.write("          }\n");
      out.write(" \t\t    });\n");
      out.write("\t</script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
